### ISSUE TITLE
Failed detection of abstract class possibly due to operation types

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#366]
This issue is related to type checker errors when attempting to instantiate abstract classes.

If a subclass does not implement any of the  `is subclass responsibility` operations then the subclass is itself abstract and should not be instantiated. The type checker normally detects this and issues an error when you try to invoke the constructor.

However, if the subclass has an operation with the same name as the super class but different parameters, then no error is issued.

Here is a minimum example:

```
class A
operations
public op : int ==> int
op(x) == is subclass responsibility
end A

class B is subclass of A
operations
public op : int * int ==> int
op(x,-) == return x+1
end B 

class Test
instance variables
x : A := new B();
operations
public test : () ==> int
test() == x.op(1);
end Test
```

For reference, I tested this in test build 140: commit 09a6683

**Comment by ldcouto** [comment]
Arise, ancient bug report!

There is still no real progress on this. I think we need to come to a decision and address this one way or another.

This is a very annoying bug. I'm currently in the process of refactoring a class hierarchy and cannot rely on the type checker at all to help me identify which subclasses still need to be addressed.

Has any further thought been given to banning overloads? I was talking to @lausdahl the other day and there some issues in C code generation that would also be helped by that.

**Comment by nickbattle** [comment]
I'm not sure what you mean by "banning overloads". VDMJ takes the C++ position that inherited names should not "mix" with locally defined names in the overloading mixture; rather a local name hides all the (otherwise) inherited names. There was a bug (now fixed), where the type checker enforced this, but the runtime environment did not, which could lead to problems with union types (where the TC could not know which type would be passed at runtime, and therefore could not decide the static binding).

I'll look at it again, while it's relatively fresh in my mind from the bug above. But perhaps you can see the problem: it is hiding the abstract inherited name because of the local definition, but that then also hides the fact that the inherited definition needs to be overridden to avoid leaving an abstract class. So it looks like the hiding needs to be a bit more intelligent!

**Comment by ldcouto** [comment]
Now I'm not sure what you mean. If a local name hides an inherited name, is that not them mixing? 

Banning overloads means you cannot overload an operation, inherited or otherwise.

**Comment by nickbattle** [comment]
We want overloads (two or more ops/fns of the same name, with distinguishable parameters). We obviously must have overrides (subclass specializing the same name/params from a parent) and inheritance. But it's not clear what to do if you inherit a name that "overloads with" a local name. In C++, the inherited name is hidden in this case, so there is only the local name (and any local overloads) visible. I think Java mixes inherited names with local overloaded names.

Anyway... I just had a look at this and made an experimental tweak. VDMJ now does the following for your test spec:
```
Parsed 3 classes in 0.172 secs. No syntax errors
Error 3330: Cannot instantiate abstract class B in 'Test' (test.vpp) at line 15:10
Unimplemented: op(int ==> int)
Type checked 3 classes in 0.011 secs. Found 1 type error
```
But unfortunately a dozen or more of the CSK test suite tests are giving unusual errors, so I need to work through these and figure out whether they are right or not.

**Comment by ldcouto** [comment]
Why do we want overloads?

**Comment by nickbattle** [comment]
Well, it's a fair question. I suppose it is "natural" to have several operations that do the same thing, but do it with different parameters, and you would "naturally" want to give them the same name and let the compiler work out the binding. Otherwise you'd have to call them procInt, procChar, procObject etc.

But perhaps that wouldn't be so bad. They're not super essential, but they're very common in languages (OO and otherwise).

**Comment by ldcouto** [comment]
Yeah, I know the question was kind of obtuse.

But I was just trying to make the point that there is a cost to be paid for having overloads and, like you said, there is a relatively simple workaround for the users. So maybe we should not just say that we must have them.

In SL, overloads yield a "duplicate definition" warning. And if you try to run the ops, they both give an error. That's actually pretty great :)
```
> p op(1)
Error 4087: Cannot convert 1 (nat1) to char in 'DEFAULT' (LaunchConfigurationExpression) at line 1:1
Runtime: Error 4087: Cannot convert 1 (nat1) to char in 'DEFAULT' (LaunchConfigurationExpression) at line 1:1
> p op('a')
Error 3064: Inappropriate type for argument 1 in 'DEFAULT' (LaunchConfigurationExpression) at line 1:1
Expect: int
Actual: char

```

**Comment by nickbattle** [comment]
It's true that there is no overloading in SL. In fact, I'm surprised it's only a warning. You could make the case for removing overloading from VDM++/RT (on the grounds of simplicity) and put it to the LB as an RM. But one clear objection would be that it is removing a fairly fundamental part of the language that many existing models depend on. (A better RM would be to define the rules formally! But perhaps we will get that with the UTP model?)

In the meantime, this issue is clearly a bug and I ought to fix it :)

**Comment by peterwvj** [comment]
I think it would be much better if we change duplicate definitions in SL to produce a type error instead of a warning. Is there a good reason why it is not like this? If you agree I can set up an issue for this.

**Comment by ldcouto** [comment]
What do the semantics say?

**Comment by nickbattle** [comment]
(I'm not sure what the official SL specification says. What does VDMTools do? It's quite good with SL).

I think I have a fix for this bug in VDMJ. I should port to Overture fairly easily. Maybe over the weekend.

**Comment by peterwvj** [comment]
For the spec below you get an error and no warnings:

~~~
Error List: 1Error, 0 Warnings
...\Dup.vdmsl, l. 8, c. 13:
  Operation already defined
~~~

~~~
operations

op: () ==> ()
op() == skip;

op: () ==> ()
op() == skip;
~~~

I thinks this is sensible.

**Comment by ldcouto** [comment]
I think we should do the same. At least for SL.

**Comment by peterwvj** [comment]
Yes, I agree. If Nick agrees too then I'll set up an issue suggesting that we make Overture do the same.

I should mention that if you do a similar thing for `values `you only get a *warning*:

~~~
...Dup.vdmsl, l. 5, c. 1:
  Warning[100] : "x" is multiple defined, and must have the same value
~~~
~~~
values

x = 1;
x = 2;
~~~

However, if you do it for type definitions then you get an *error*

~~~
...\Dup.vdmsl, l. 5, c. 9:
  Type already defined
~~~
~~~
types

N = nat;
N = char;
~~~

**Comment by nickbattle** [comment]
OK, by all means raise a separate issue about the SL errors - though it seems the requirement may be more subtle than we knew :)

I'm about to push a fix for this bug.

**Comment by nickbattle** [comment]
Hmmm... looks like there is still a problem with this. So I'll remove the mergable flag!

**Comment by nickbattle** [comment]
Right! I now think this is fixed, but it's been another "experience" of the subtle differences between VDMJ and Overture, AST differences and LexNameToken.equals threw me for a while... But now the original spec on this issue works correctly, as well as there being some updates to the test suite results.

I'll put the mergable flag back in place :)

**Comment by ldcouto** [comment]
Works correctly means type error right?

**Comment by nickbattle** [comment]
LOL, yes, as entered above the class B is abstract, so it cannot be instantiated in the Test class and this now gives a TC error. If you change the signature in B to override the abstract operation from A, then it is fine.
