### ISSUE TITLE
Find hosting solution for Eclipse P2 update site

### ISSUE THREAD

**Issue by joey-coleman** [overturetool/overture#412]
Right now we do not have the Overture IDE using any sort of auto-update functionality, as the old Eclipse P2 update site was hosted on sourceforge, and I'm trying to remove all dependencies on them (that was the last, I believe).

However, we would like to have auto-update again, so we will need to:

* [x] Find a new place to host those files
* [x] Update `ide/product/src/main/resources/overture.p2.inf` to include an `addRepository` line (see <https://wiki.eclipse.org/Equinox/p2/Adding_Self-Update_to_an_RCP_Application>)

Finding a new place to host these files is not trivial — the Eclipse community doesn't have a standard repository like the main Maven repositories (which are unsuitable for this).  GitHub is sometimes used, but I believe it's discouraged, and we have the problem that some of the jars are very large (making it difficult to use GitHub for this anyway, due to file size constraints).

**Comment by nlmave** [comment]
some suggestions:
make update.overturetool.org available as a WebDAV services hosted 
directly from our AU buildserver?
alternatively, deploy via a public accessible dropbox shared folder 
(free up to 2GB)
or host it on Amazon S3 services (free up to 5GB)

**Comment by joey-coleman** [comment]
For the first, I've been trying to avoid using the AU buildserver for general download purposes — upload out of AU's networks is occasionally throttled, and I'd rather not have AU IT go after Peter about a random bandwidth spike.  Also, I'm not at all sure why we'd need webdav opened up; not only is it a broader attack surface with respect to security holes (remember that it's not IT doing primary admin of that machine!), but we have direct filesystem access with Jenkins itself.  Where we to use the buildserver for Eclipse updates, it would be done as a Jenkins job that does direct deployment.

Dropbox could potentially work, but it would ideally need some sort of API integration, and I'm not aware of what, if anything, is available.

Amazon S3 is the best option of the set, in my opinion, and I wasn't aware of any permanent free service level (I know that there's a free tier limited to one year; I've made use of it in the context of personal backups).

Using `update.overturetool.org` is a good idea, as it gives indirection and flexibility.

Regardless of the option chosen, the task will need a champion, as a robust setup isn't as simple as throwing some files up to a server.  Eclipse P2 repos are, as I understand it, supposed to be merged –not unlike Maven repos– rather than just replaced.  As usual, however, the documentation at Eclipse is less clear than one would prefer.

**Comment by lausdahl** [comment]
we need to update the release doc about the update site:

The default for development is

~~~
 addRepository(type:0,name:Overture,enabled:false,location:http${#58}//dl.bintray.com/overturetool/overturetool/);\
  addRepository(type:1,name:Overture,enabled:false,location:http${#58}//dl.bintray.com/overturetool/overturetool/);\
  addRepository(type:0,name:Overture Development,enabled:true,location:http${#58}//dl.bintray.com/overturetool/overturetool-development/);\
  addRepository(type:1,name:Overture Development,enabled:true,location:http${#58}//dl.bintray.com/overturetool/overturetool-development/);
~~~

however we need to switch the two enabled booleans for the release/development. Maybe we can automate this but haven done that yet.

**Comment by ldcouto** [comment]
The file for the aforementioned change is  `ide/product/src/main/resources/overture.p2.inf`

**Comment by lausdahl** [comment]
We use this script to uploading to bintray https://github.com/vogellacompany/bintray-publish-p2-updatesite/

**Comment by ldcouto** [comment]
So, this is now a part of the 2.2.2 release. However, I propose we keep quiet about it for now.

When we do the next release, we should try to update from within the tool and if it works well, we can announce it in the next release notes.

**Comment by peterwvj** [comment]
Cool, Luis - good job you did - congratulations on loosing your OVT release virginity :)

**Comment by ldcouto** [comment]
First off... eww!

Also, this is the second time I've done an Overture release.

**Comment by ldcouto** [comment]
So, I tried the auto-update. It was all going great until it died trying to update some of the documentation.

```
An error occurred while configuring the installed items
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Configure, operand=[R]org.overture.ide.platform.product 2.2.2 --> [R]org.overture.ide.platform.product 2.2.4, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CopyAction).
I/O Error while copying /home/jenkins/jenkins/jobs/overture-master/workspace/ide/product/../../externals/documentation/target/documentation-master/documentation/QuickOverviewVDMPPOperators/QuickOverviewofVDMOperators.pdf - see details.
Source: /home/jenkins/jenkins/jobs/overture-master/workspace/ide/product/../../externals/documentation/target/documentation-master/documentation/QuickOverviewVDMPPOperators/QuickOverviewofVDMOperators.pdfdoes not exists
```

I imagine this needs some more fine tuning but I think the overall thing works.

**Comment by ldcouto** [comment]
@lausdahl  this is working now, yeah?

**Comment by lausdahl** [comment]
Self-updating is not working because of these lines: 
- https://github.com/overturetool/overture/blob/development/ide/product/src/main/resources/overture.p2.inf#L2-11
- https://github.com/overturetool/overture/blob/development/ide/product/src/main/resources/overture.p2.inf#L13-14

I understand why this was done like this but it needs to be removed to make the update p2 repo useful. These lined are executed once product is updated and the local user does not have these build server relative paths on his machine.

If these lined are removed form here the self-update should complete just fine. We are pushing to:

- Development: https://bintray.com/overturetool/overturetool-development/overture-ide/view#files
- Release: https://bintray.com/overturetool/overturetool/overture-ide/view#files

**Comment by ldcouto** [comment]
So, do we take those items out of the product? We can put them in the
release zip instead.

**Comment by lausdahl** [comment]
The answer can be found here: 

- http://stackoverflow.com/questions/17566380/dynamically-adding-a-file-to-a-product-archive-built-by-tycho

> The article you linked deals with removing files from a product distribution archive, which can be quite challenging. Adding files to a distribution archive is a lot simpler, and doesn't require any of the low-level p2 hacking described in the article.

>In order to add a file to a product distribution archive, include add it as as root files to one of the features included in your product:

>In the build.properties of the feature build, add a line root=file:target/rootfiles/**
Add goals in the pom.xml of the feature build so that the file(s) you want to have included in the distribution archive are copied/added to the target/rootfiles folder during the build. E.g. the maven-resources-plugin or the maven-dependency-plugin could do this.
When the feature with the root files configuration is added to the product, the files you have put into target/rootfiles will end up in the product distribution archive.

>In case you have problems with this, you also may have a look at this [example project](http://git.eclipse.org/c/tycho/org.eclipse.tycho-demo.git/tree/itp04-rcp).

- http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_rootfiles.htm

However, tycho even in version `0.25.0` still dont support the nested folders: See feature list https://eclipse.org/tycho/sitedocs/BuildProperties.html and this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=386263

This essentially says that we hacked it before so lets remove the hack:
- [ ] add artefact for docs
- [ ] add artefact for release notes
- [ ] correctly pack commandlinetools artefact
- [ ] update the RCP feature
- [ ] remove hack from https://github.com/overturetool/overture/blob/development/ide/product/src/main/resources/overture.p2.inf#L2-14

**Comment by Bananeweizen** [comment]
You may want to reopen this issue. Bintray is shutting down. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
