### ISSUE TITLE
Potential issue with addition of reals

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#439]
So, according to Overture `0.1 + 0.2 = 0.30000000000000004`.

Is this some weird thing with precision, something obvious that I'm missing or is Overture bad at math?

**Comment by nickbattle** [comment]
It's the same in VDMJ. I'm surprised, but in principle real numbers that don't 
have a precise representation in a double cannot reliably be added with the 
precision you would expect. Interestingly, the arbitrary precision extension for 
VDMJ is precise (because these are turned into BigDecimals, which are 
BigIntegers with a decimal point somewhere, and so precise).

**Comment by ldcouto** [comment]
The funny thing is it only happens around 0.3. You can add 0.1 to 0.1 and get 0.2. Of course, it may happen in lots of other additions, I've just not tested.

Any thoughts on what, if anything we'll do about this? I see the point about precision but aren't reals in the VDM semantics precise? Maybe we should add the precision extension to Overture. This issue actually caused problematic behaviour in a model.

**Comment by nickbattle** [comment]
I can't remember how exponent/mantissa stuff works, but presumably some numbers 
can be represented precisely and some can't.

**Comment by ldcouto** [comment]
So, this is not really an issue. Just something you have to be aware of. In the future, provided there's a real need, we'll consider migrating the precision version of VDMJ to Overture.
