### ISSUE TITLE
RESULT is not really reserved

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#443]
The LRM says that "In the post-condition of explicit function and operation definitions the result value must be referred to by the reserved word RESULT"

But RESULT does not really seem to be reserved. For example, in the spec below function `f` uses it as a paramater name. Since the result of the function is also referred to using `RESULT` you get a warning saying that the parameter is being hidden: `- RESULT at 6:4 hidden by RESULT. `

Also, executing 
~~~
A`f('b')
~~~

Gives the following error

~~~
Error 4053: Parameter patterns do not match arguments in 'A' (LaunchConfigurationExpression) at line 1:1

Main 206: Error evaluating code
Detailed Message: Error 4053: Parameter patterns do not match arguments in 'A' (LaunchConfigurationExpression) at line 1:1

Stack trace:
	#0 file:/home/peter/dev/runtime-Ovt/ResWords/LaunchConfigurationExpression [1]
~~~

On the other hand, executing `A`f2('b')' i.e. yields  `2'

~~~
module A
definitions

functions
f :  char -> real
f (RESULT) == if RESULT = 'a' then 1 else 2 --line 6
post RESULT = 2;

f2 :  char -> real
f2 (res) == if res = 'a' then 1 else 2
post RESULT = 2;


end A
~~~

I think it makes most sense not to allow identifiers to be declared using RESULT as the name.

**Comment by nickbattle** [comment]
Good spot. I don't think that RESULT is reserved in the usual sense (it isn't a keyword), though perhaps it should be. Though syntactically and semantically it behaves as a variable, so it might be better to give an error when a variable named RESULT is defined rather than literally making it a reserved word. Strange error you're getting though.

I tried your spec in VDMTools. Not only does it not give type errors, it actually works:
```
>> p f('b')
2
```
So it looks like the value of RESULT is being overwritten and type-changed on the fly!

I'll take a look at VDMJ.

**Comment by nickbattle** [comment]
The reason you get that interesting error is that VDMJ is having problems calling the postcondition function. The post_f function is effectively defined as follows:
```
post_f: char * real +> bool
post_f(RESULT, RESULT) ==
    RESULT = 2;
```
Here, the first parameter is the one from the function, and the second parameter is the usual "RESULT" which is always passed (by that name) to the post_f. The error then makes some sense: the value of RESULT is both 'b' and 2, but these are different types and values, so although you can have two function parameters with the same name, you cannot have them with different types/values at runtime!

So if I can fix this, I have to be careful not to make postcondition functions suddenly illegal for using "RESULT" as a parameter name.

**Comment by peterwvj** [comment]
I get your point about RESULT not being a reserved word in the usual sense. If we decide to allow use of RESULT as a parameter name (like VDMTools) then maybe the LRM needs a small tweak. But allowing RESULT as a parameter name still seems to make the tool situation complicated. I am not sure how you would avoid the pattern matching situation causing the error. 

That said I am still in favor of not allowing RESULT as a parameter name. I find it a bit confusing. I'll keep an open mind if somebody thinks differently about this :)

**Comment by nickbattle** [comment]
It would presumably be possible to add a flag parameter somewhere to mean "dis/allow RESULT definitions", and then set that flag when processing the generated postcondition function. But I really hate doing things like that (even though there are several in VDMJ already!).

The warning is pointing to the problem, though it is a confusing message, and I agree a warning is a bit weak for what is really an error.

One point is that the post_f function ought not to type check cleanly because the TC should know that the two occurrences of RESULT are disjoint types (ie. cannot be the same value). I'll see whether it is easy to strengthen that check. It would only catch parameters though. People would still be able to say "let RESULT = ... " inside post expressions, and would only get a warning.

**Comment by nlmave** [comment]
> It would presumably be possible to add a flag parameter somewhere to mean
> "dis/allow RESULT definitions", and then set that flag when processing the
> generated postcondition function. But I really hate doing things like that
> (even though there are several in VDMJ already!).
>
> The warning is pointing to the problem, though it is a confusing message,
> and I agree a warning is a bit weak for what is really an error.

Following this thread as an "outsider" I agree that this should be flagged
as a type error, as the use of RESULT as a free variable name should be
discouraged in any case, as it has a specific meaning in implicit
operations. And the LRM should be updated to make this point specifically.

Anyway, my 2 cents worth.
Marcel

**Comment by nickbattle** [comment]
I found a place where I can add a check, just after definitions are declared. The advantage is that this catches parameter names as well as in-line definitions (like "let RESULT = 1 in ..."). Luckily, postcondition functions are not type-checked in quite the same way as regular functions (otherwise they would complain that "RESULT" was unused, if the post expression did not use it), and so this also means that postconditions do not cause problems.

**Comment by nickbattle** [comment]
Now fixed in ncb/development.
