### ISSUE TITLE
Proof Obligation Explorer not showing status

### ISSUE THREAD

**Issue by E-Hermo** [overturetool/overture#468]
I'm using Overture 2.2.6. According to OvertureIDEUserGuide.pdf in the documentation, each item in the Proof Obligation Explorer should have four components. The last one, <em>a status field indicating whether the proof obligation is trivially correct or would have to be proved by a proof engine</em> is not appearing when generating proof obligations 

Am I missing something?

**Comment by nickbattle** [comment]
Confirmed. This appears to be missing in 2.2.6 - presumably not as a deliberate change, Luis!?

**Comment by nickbattle** [comment]
Or perhaps this feature was never ported over to "new POG", since it depended on string pattern matching, and the new POs are built of AST stuff?

Eduardo, this wasn't a very powerful proof feature in fact. It's just that several proof obligations are "obvious" and conform to a simple pattern that can be recognised. The PO generator (POG) in earlier versions of Overture produced snippets of VDM source (strings) which could be compared with the trivial POs using a simple pattern match. The latest versions of Overture generate POs as complete subtrees of AST types, which is more powerful but harder to recognise trivial structures. This may have been when the feature was dropped (and we forgot to update the IDE guide).

**Comment by E-Hermo** [comment]
Hi Nick, I've found <a href="https://github.com/overturetool/overture/issues/441">this</a> so, I guess you're right. 

Thanks!

**Comment by peterwvj** [comment]
#441
