### ISSUE TITLE
Empty block does not get detected

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#480]
In the example given below the type checker does not detect that the `else` branch is an empty block (which is illegal). What's even more odd is that the spec type checks without any errors. This problem only happens in Overture - VDMJ reports the problem with the empty block.
~~~
peter@peter-ubuntu:~/dev/vdm_tools$ cat M.vdmsl 
operations

op: () ==> ()
op () ==
(
  if true then
   a := a + 1
  else
  ()
);
peter@peter-ubuntu:~/dev/vdm_tools$ java -jar vdmj-3.0.1.jar -r vdm10 -vdmsl M.vdmsl 
Error 2296: Block cannot be empty in 'DEFAULT' (M.vdmsl) at line 9:3
Parsed 1 module in 0.129 secs. Found 1 syntax error
peter@peter-ubuntu:~/dev/vdm_tools$ java -jar ~/dev/ovtrepo/core/commandline/target/Overture-2.3.1-SNAPSHOT.jar -r vdm10 -vdmsl M.vdmsl 
Parsed 1 module in 0.068 secs. No syntax errors
Type checked 1 module in 0.062 secs. No type errors
peter@peter-ubuntu:~/dev/vdm_tools$ 
~~~

**Comment by nickbattle** [comment]
This is interesting. The logic (in the statement reader, part of the parser) is slightly different between Overture and VDMJ in this area. If you make Overture the same as VDMJ, then it works as expected. So the change was presumably made for some reason, but changing it fixes the problem. Unfortunately, the Overture test suite runs with (and without) the change, so that's not helping me. And the change is present in the oldest version of the file I have in Git (3 years old).

I suggest I commit this change and we just keep an eye out for empty block or block ending problems?

**Comment by nickbattle** [comment]
Now fixed in ncb/development.

Incidentally, the problem was revealed because of the outer block. If the operation was just a bare "if" statement without the block, then the empty else was correctly reported.

**Comment by peterwvj** [comment]
Yeah that's what I noticed. 

Thanks for fixing this.
