### ISSUE TITLE
VDM project

### ISSUE THREAD

**Issue by bakalindro** [overturetool/overture#486]
Hi everybody, 

I've been working on coursework but have an issue trying to finish these files any help will be appreciated, thanks. 

It should be simple but I just can't get a concept of it and other work just drives me nuts. 

[VDM.zip](https://github.com/overturetool/overture/files/52990/VDM.zip)

**Comment by nickbattle** [comment]
Unless you're saying that there is a bug related to Overture here, we don't really want a new GitHub issue to track your problem. If you want to discuss how to solve a normal problem with a specification, you're welcome to post to overture-users@overturetool.org. And it would help if you could post your specification in plain text rather than zipped RTF files :-)
