### ISSUE TITLE
Union pattern match failure 

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#502]
Minimal example:
```
p let ({} union {}) union {} = {} in 1
= 1
```

See https://github.com/overturetool/documentation/issues/9 for more

**Comment by nickbattle** [comment]
The problem is caused by the fact that the brackets make the LHS into an expression pattern, and these were always considered to be "length 1" (ie. yielding a set with one member in this context). In fact an expression can clearly result in an arbitrary length, including zero. So the length for an expression pattern should be ANY.

**Comment by nickbattle** [comment]
Now available in ncb/development.
