### ISSUE TITLE
POs are not generated with unions of records where fields only work for some of them.

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#510]
For a VDM++ specification such as
~~~
class A 
types
    Car ::  speed : int
            doors : int;
    Spacecraft :: speed : int ;

    Vehicle = Car | Spacecraft;
    
instance variables
    bar : Vehicle := mk_Spacecraft(4000);

operations
    public Run : () ==> int
    Run() == return bar.doors;
    
end A
~~~
no POs are generated. However, since thie yield a run-time error a PO should really be generated in cases such as this.

**Comment by nickbattle** [comment]
This is an interesting case. Internally, the Vehicle type is a record (because all of its components are), and the agreggated fields - that could "possibly" be used, in the sense of possible semantics - is "speed:int" and "doors:int". The PO subtype check on the return from the the Run operation then compares the (possible) type of "doors", which is int, with the required return type, int, and so generates no POs.

I'll have to think of the best way forward here. It might just be that the type of doors ought to be something like "int | unknown", which would force the PO.

VDMTools does report this correctly :-)

**Comment by pglvdm** [comment]
The way this is handled inside VDMTools (or at least was when I was still in charge of it) was to walk over the AST again and use a definite-semantics approach whenever run-time errors could not be guaranteed. If you introduce the "int | unknown" type inference you would also need to look up and determine what caused the "unknown" aspect to occur in the first place...

**Comment by nickbattle** [comment]
Well, what is the correct PO here? I think the "int | unknown" approach would produce a PO that says "is_(bar.doors, int)".

**Comment by pglvdm** [comment]
ohh yes, that is indeed correct. So if we add such "unknowns" to the decorated AST the main point is to get other tools such as the code generator to ignore them.

**Comment by nickbattle** [comment]
I also need to check that the type checker is happy, since a union with an unknown type would be unusual. I'll mention this to @peterwvj.

**Comment by peterwvj** [comment]
Below is the output currently produced by the Java code generator (or the relevant part at least)

~~~
    /* M.vdmpp 13:12 */
    public Number Run() {
        /* M.vdmpp 14:21 */
        Number apply_1 = null;

        if (bar instanceof Car) {
            apply_1 = ((Car) bar).doors;
        } else {
            throw new RuntimeException("Missing member: doors");
        }

        /* M.vdmpp 14:14 */
        return apply_1;
    }
~~~

If you change the type of bar.doors to `int | ?` then I think the Java code generator will produce:

~~~
    /* M.vdmpp 13:12 */
    public Number Run() {
        /* M.vdmpp 14:21 */
        Object apply_1 = null; // PVJ: Use java.lang.Object

        if (bar instanceof Car) {
            apply_1 = ((Car) bar).doors;
        } else {
            throw new RuntimeException("Missing member: doors");
        }

        /* M.vdmpp 14:14 */
        return (Number) apply_1; // PVJ: Narrow the return value
    }
~~~

**Comment by nickbattle** [comment]
OK, looks like this might work then. I'll try to make the PO changes when I get a minute.

**Comment by nickbattle** [comment]
It looks like this does work, but the PO is generated because the return type of the operation is a subtype of the type of the body (which is now "int | unknown"). So the PO is generated as "is_int(RESULT)". But then operation POs are weak generally. If you convert the operation to a function, then the PO is far more sensible:
```
(forall bar:Vehicle &
  is_int((bar.doors)))
```
Also, I could not use UndefinedType or UnknownType as the type comparator already has special rules for those which excludes them from subtype checks. So I created an "impossible" quote type called <?> for the missing fields. That works, and you can't legitimately use this type in a spec, so I think it's safe. But the code generator may have to watch out for it?

**Comment by peterwvj** [comment]
If I understand you correctly then I think we should be fine. If you push it to some branch then I could try to play around with it.

**Comment by nickbattle** [comment]
I've only applied it to VDMJ at the moment, but it should transfer to Overture fairly easily - just an update to UnionType. I'll try to push it early tomorrow.

**Comment by peterwvj** [comment]
Sounds good, thanks!

**Comment by nickbattle** [comment]
I have a patch, but it's breaking the code generator tests - perhaps as expected. Can you apply this and have a look (I'm reluctant to commit something that breaks the build)?

(I'll email the patch... GitHub won't let you attach them!)

**Comment by peterwvj** [comment]
I applied Nick's patch and it seems to work. I had to update the code generator to take the new type into account, but that was not much of a problem.
