### ISSUE TITLE
Overture displays warning instead of error when accessing field of record

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#520]
Consider the following module
```
module record
exports all
definitions 
types 
  A :: b:[B];
  B :: m:nat n:nat;
functions 
  f: A -> nat
  f(a) == let b = if a.b=nil then mk_B(0,0) else a.b
          in b.m + b.n + b.x;--WARNING
end record
```
When presented to Overture the expression `b.x` is flagged with a warning "Unknown field x in record ?." This should be an error since `x` is not a field of `B`. In other situations the field `x` is flagged as an error.

**Comment by nickbattle** [comment]
This is due to a bug in the way type unions are handled. The "b" value is either of type B or [B], which is actually the same as [B]. But the value was treated as "B | [B]" which ends up producing a warning in the (mistaken) belief that some type in the union could define the field. Correcting the union creation, to treat B | [B] as [B], results in the error behaviour expected:
```
Error 3090: Unknown field x in record B in 'DEFAULT' (test.vdm) at line 7:28
```

**Comment by nickbattle** [comment]
Now fixed in ncb/development.
