### ISSUE TITLE
Java code generator does not put doubleValue() to a temporary variable for if-statement

### ISSUE THREAD

**Issue by tomooda** [overturetool/overture#525]
Given the following fragment of spec,

```
operations
   op : () ==> ()
   op() == (dcl x:real := 0.0;
           x := x * 2 + if x > 10 then 1.0 else 2.0);
```

a Java code like the below will be generated

```
    public static void op() {
        Number x = 0.0;
        Number ternaryIfExp_1 = null;

        if (x.doubleValue() > 10L) {
            ternaryIfExp_1 = 1.0;
        } else {
            ternaryIfExp_1 = 2.0;
        }

        x = (x.doubleValue() * 2L) + (ternaryIfExp_1);
    }
```

resulting in a type error on "+" unless the last line is replaced with

```
        x = (x.doubleValue() * 2L) + (ternaryIfExp_1).doubleValue();
```

**Comment by peterwvj** [comment]
Thanks for reporting Tomo. The code generator missed a few cases for situations where it needs to deference some expression in order to obtain its numeric value.

Your example now produces

~~~
x = (x.doubleValue() * 2L) + (ternaryIfExp_1.longValue());
~~~

It's dereferenced using `longValue()` because the type checker sets `nat1` as the type of ternary-if expression (or something like that).

**Comment by peterwvj** [comment]
In case it's helpful the test build available at http://overture.au.dk/overture/test/Build-32_2016-03-30_15-56/ contains this fix. A lot of stuff has changed recently so this build requires Java 8 and uses Eclipse Mars (instead of Luna) to build Overture.
