### ISSUE TITLE
Call by value semantics is not respected

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#544]
With a model such as:
~~~
class A

types
 
 Vector2D ::
   x : nat
   y : nat
operations
public op : () ==> nat
op () == (
dcl v1 : Vector2D := mk_Vector2D(1,2);
dcl v2 : Vector2D := v1; -- Copy using value semantics
v1.x := 2;
return v2.x;)

end A
~~~
one can call "new A().op()" which shouyld yield "1" but it yield "2"!!!!

**Comment by nickbattle** [comment]
This was caused by an attempt to optimize UpdatableValue creation, by re-using an object if it was already updatable in some circumstances. Clearly this wasn't correct. I've pished a fix to ncb/development and to the test branch, so a build will be automatically created in a few minutes.

It's strange that we've not noticed before, though the actual circumstances where it causes a problem may be limited - the fact that Vector2D was a record and having a field changed was important, for example. The test spec now produces the value 1 as expected.
