### ISSUE TITLE
could not find or load main class org.overture.interpreter.debug.DBG Reader V2

### ISSUE THREAD

**Issue by fanabba** [overturetool/overture#566]
I cannot get the Overture Tool to run on my Lenovo Core i5 ThinkPad/Ultrabooh,
running the 32-bit Windows 7.

I keep getting the error:

could not find or load main class org.overture.interpreter.debug.DBG Reader V2

**Comment by ldcouto** [comment]
We need a bit more info to help diagnose the problem. What version of Overture are you running and what version of Java do you have installed?

**Comment by peterwvj** [comment]
Based on the error message it sounds like one of the binary files cannot be loaded. Can you rule out the possibility that this is not caused by a process (e.g. antivirus) that prevents the `.class` file from being loaded? It might also be that something went wrong when you extracted the Overture zip file. Also, where did you install Overture? I've seen people getting very strange errors on Windows when they run Overture from a location where the user has limited rights.

As a Sanity check, could you try to download the version of Overture that is causing you problems, then extract it to some location were you have read/write rights (e.g. the desktop) and run Overture again.

**Comment by peterwvj** [comment]
Right now I don't have a Win32 machine available to test the tool. I may have one available at work tomorrow.

**Comment by fanabba** [comment]
Thank you.

I should add that the Overture tool works fine on a Dell Core i2   32-bit Windows 7 laptop.
It is just my Lenovo 32-bit Windows 7 Core i5 laptop (ThinkPad/Ultrabook) that has problems.

Thanks again. 

 

 

-----Original Message-----

**Comment by fanabba** [comment]
I have Java 8 installed and I am running  Overture-2.3.6-win32.win32.x86.
I should add that it is my Lenovo 32-bit Windows Intel  Core i5 computer running 32-bit Windows 7 that gives the error when debugging/running. 
Everything works fine on a Dell Intel Core i2 laptop  running 32-bit Windows 7.

Thank you.
 
 

 

-----Original Message-----

**Comment by fanabba** [comment]
I have extracted the downloaded file into a folder where I have full rights. The anti-virus does not seem to be an issue.  
I am running the Overture tool on a 32-bit Windows 7 installation running on a Lenovo Intel Core i5 (Ultrabook/ThinkPad) and I have the error.
Everything works fine  on a 32-bit Windows 7 installation running on a Dell Intel Core i2.

Thank you.
 
 

 

-----Original Message-----

**Comment by peterwvj** [comment]
I tried running Overture-win32 on a win32 machine. After I had installed Java 8, I tried to execute different VDM models, and surprisingly Overture produced very strange errors: either it would hang, or complain about Java versions.

Then I noticed that I already had Java 7 installed on my machine. When I removed the Java 7 dependency, Overture was able to execute VDM models. Somehow the Java 7 and Java 8 installations got Overture/Eclipse confused. Could this be your problem? I know for a fact that multiple Java installations on a Windows machine often causes a mess so I'm wondering if this could be your problem?

I mean, if you open `Control Panel\Programs\Programs and Features` do you see multiple Java installations?

**Comment by nickbattle** [comment]
We had a similar problem reported by email recently, 32-bit Win7 on Lenovo kit:

Dear Prof. Larsen:

Here is more information, if it is of any interest to you.

The 32-bit Windows version of Overture version 2.3.6 works fine on  Dell Intel Core 13 computer with a 32 bit Windows 7 operating system, but does not work on a Lenovo Thinkpad Intel Core 15 computer running a Windows 7 32-bit operating system. Because of this, I was having problems. I will just have to switch to a hardware that can run Overture.
(snip)
There are no errors any more in any of the files, but when I try to run the Run() operation  from class Test1, I get the following error:

**
** Overture Console
**
Error: Could not find or load main class org.overture.interpreter.debug.DBGPReaderV2

**Comment by nickbattle** [comment]
I have a Lenovo T420 (i5), but I use Linux. It is fine with 32-bit and 64-bit kernels, so it is more likely a Windows/Java problem than the raw hardware.

**Comment by peterwvj** [comment]
@fanabba Did you report this problem to Peter Gorm Larsen? Not sure, but this could be related to Issue #429

**Comment by fanabba** [comment]
Thank you for your reply.
I checked  and found only Java 8 installed (no Java 7). Still, I get the error.

 

 

 

-----Original Message-----
From: Peter W. V. Tran-Jørgensen <notifications@gith
ub.com>
To: overturetool/overture <overture@noreply.github.com>
Cc: fanabba <fanabba@aol.com>; Author <author@noreply.github.com>
Sent: Thu, Jun 2, 2016 2:57 am
Subject: Re: [overturetool/overture] could not find or load main class org.overture.interpreter.debug.DBG Reader V2 (#566)



I tried running Overture-win32 on a win32 machine. After I had installed Java 8, I tried to execute different VDM models, and surprisingly Overture produced very strange errors: either it would hang, or complain about Java versions.
Then I noticed that I already had Java 7 installed on my machine. When I removed the Java 7 dependency, Overture was able to execute VDM models. Somehow the Java 7 and Java 8 installations got Overture/Eclipse confused. Could this be your problem? I know for a fact that multiple Java installations on a Windows machine often causes a mess so I'm wondering if this could be your problem?
I mean, if you open Control Panel\Programs\Programs and Features do you see multiple Java installations?

**Comment by fanabba** [comment]
Yes, I did report it to Prof. Larsen.

 

 

-----Original Message-----

**Comment by fanabba** [comment]
Thank you. 
 

 

 

-----Original Message-----

**Comment by peterwvj** [comment]
Now that we've confirmed that  Overture win 32 works on Windows 32 I'm more confident that this has something to do with your security settings or the Java installation. Did you try to run Overture with your Antivirus or firewall turned completely off?

**Comment by nlmave** [comment]
Peter W. V. Tran-Jørgensen schreef op 2016-06-02 12:11:
> Now that we've confirmed that Overture win 32 works on Windows 32 I'm
> more confident that this has something to do with your security
> settings or the Java installation. Did you try to run Overture with
> your Antivirus or firewall turned completely off?

I've had similar problems with other tools on Win32, some more things to 
check:
- is your user-id part of the local administrator group? if not, add the 
user to this group
- check the security properties of the Overture installation directory 
(and all subdirs);
   select the directory in Windows Explorer - right click - properties - 
security tab - [Advanced]

Hope this helps to diagnose the issue. For what it is worth, I'm running 
Overture on W7 (32 and 64 bit) and W10 (64-bit) without any problems 
whatsoever.

**Comment by peterwvj** [comment]
@fanabba Has any of the security/antivirus related suggestions helped you solve this problem?
