### ISSUE TITLE
Type check of break point conditions is missing

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#567]
If you set a conditional breakpoint at the `skip` statement in the `getX` operation in the `B` class and you debug the model the interpreter crashes.

```
class A

instance variables

x : nat := 1;

operations

public getX : () ==> nat
getX () == return x;

end A


class B

operations

public Run : () ==> ()
Run () ==
let a = new A()
in
  getX(a);

public getX : A ==> ()
getX (a) == 
 skip; -- set conditional break point with condition a.getX() = 2

end B
```

If you inspect it internally you'll will see that this is caused by a `NullPointerException` that is thrown when it tries to evaluate the condition of the break point `a.getX() = 2`.

```
java.lang.NullPointerException
	at org.overture.interpreter.assistant.expression.AFieldExpAssistantInterpreter.evaluate(AFieldExpAssistantInterpreter.java:37)
	at org.overture.interpreter.eval.ExpressionEvaluator.caseAFieldExp(ExpressionEvaluator.java:375)
	at org.overture.interpreter.eval.ExpressionEvaluator.caseAFieldExp(ExpressionEvaluator.java:1)
	at org.overture.ast.expressions.AFieldExp.apply(AFieldExp.java:349)
	at org.overture.interpreter.eval.ExpressionEvaluator.caseAApplyExp(ExpressionEvaluator.java:135)
	at org.overture.interpreter.eval.ExpressionEvaluator.caseAApplyExp(ExpressionEvaluator.java:1)
	at org.overture.ast.expressions.AApplyExp.apply(AApplyExp.java:385)
	at 
```

More specifically, this problem is caused when it tries to read the member name of the `AFieldExp`  in the `evaluate` method in the `AFieldExpAssistantInterpreter` class (line 37).

```
r = ov.get(node.getMemberName(), node.getMemberName().getExplicit());
```

**Comment by peterwvj** [comment]
Looking a bit more into this it seems as if the type check of the conditional expression is missing. Looking at the `TypeCheckerExpVisitor` there are situations where the type checker will set the member name of the `AFieldExp` if it is not already set. This explains why the member name is missing.

**Comment by nickbattle** [comment]
It may be that some fields are set by the type checker, rather than the parser as such. I'm not sure whether breakpoint expressions can be checked before they are used though? (Ah... you beat me to it!)

**Comment by peterwvj** [comment]
Hehe :) Yes, I'm not sure how we solve this.

The `BreakPoint` class has `check` method that determines whether to stop the execution.

~~~
public void check(ILexLocation execl, Context ctxt)
~~~

I guess it should be possible to type check it here.

**Comment by peterwvj** [comment]
Right now I'm unsure about how we construct the environment that we need to type check the expression.

**Comment by nickbattle** [comment]
I'll try your example on VDMJ in a minute... that might give some clues (or fail in the same way!)

**Comment by nickbattle** [comment]
LOL... well, it looks like VDMJ has the same issue:
```
> break 27 a.getX() = 2
Created break [2] when "a.getX() = 2" in 'B' (test.vpp) at line 27:4
27:     skip; -- set conditional break point with condition a.getX() = 2
> p new B().Run()
Breakpoint [2]: null "a.getX() = 2"
= ()
Executed in 0.0030 secs.
>
```
I'll have a closer look over lunch.

**Comment by peterwvj** [comment]
Interesting :) Thanks for your input, Nick!

**Comment by nickbattle** [comment]
Interesting problem. VDMJ currently doesn't try to type check these stop expressions, and just executes them. If there are any errors when it is executed - including "value is not boolean" - these get logged, but execution continues.

I can't see what environment we could sensibly construct to type check them though. The expression can be anything in scope where the breakpoint is set. So to build an Environment, that would require understanding all the enclosing scopes etc. So you can see why it currently just uses the Context to execute the test (and catches/prints problems, but doesn't stop).

I would point out that doing anything significant in BP expressions - like calling an operation, as you do - is a very bad idea. Even if it was pure, I would be nervous. Note that the execution does not currently have "time stopped" around it (as other invisible calculations do, like pre/post). We ought really to do that as a minimum.

Another interesting question is about the dialect of the conditional expression. I had assumed it would be the same as the main spec, but actually it's defaulting to VDM-SL. It might otherwise have been possible to say "a.A`GetX() = 2" and avoid the problem with the memberName not being set, but this actually raises an error on VDMJ (it's not legal SL).

So lots of questions there. I would say the current advice (for users) would be to use very simple test expressions, with no object calls or operation calls, preferably just using values and variables that are directly in the Context at the breakpoint.

**Comment by peterwvj** [comment]
I applied the patch you send. I noticed that the code print the exception message when the evaluation of the break point fails:

```
String message = e.getMessage();

println("Breakpoint [" + number + "]: " + message + " \"" + trace + "\"");
```

However, since  `e`'s message is `null` for certain exceptions (e.g. ``NullPointerExceptions`) I changed it to:

```
String message = e.getMessage();
					
if(message == null)
{
   message = "breakpoint condition could not be evaluated";
}
```

**Comment by peterwvj** [comment]
VDMTools is not currently available for download and I don't have it installed on my system. Probably because they are negotiating the rights. I suggest that we put a note in the user guide mentioning this limitation and then we can close this issue. I can do that. Anybody against?

**Comment by nickbattle** [comment]
Yes, that sounds perfectly sensible. I don't think it's a big restriction. People will surely understand that you can't reasonably go calling complex operations in a breakpoint condition.

**Comment by peterwvj** [comment]
Great! Okay that's done!
