### ISSUE TITLE
Output informations of "CT Test Case result" View is not enough

### ISSUE THREAD

**Issue by shinsahara** [overturetool/overture#578]
Output informations of "CT Test Case result" View is not enough.
For example,  in attached model output window is the following PDF file.

In 'Test, 000001' of CT test T2(16) on "CT Overview" view is following:

    Traces Test case                          Result
    sL.add_user(p1)                           ()
    sL.add_user(p2)                           Error 4071: Precondition failure: pre_add_user in 'Library' at line 24:8
    ...                                                  ...

In 'Test, 000006' of CT test T2(16) on "CT Overview" view is following:

    Traces Test case                          Result
    sL.add_user(p1)                           ()
    sL.add_user(p2)                           ()
    ...                                                  ...

'Trace Test case' field of both tests are same, but 'Result' field is different.
So it is difficult to understand the cause of error.

I think that 'Trace Test case' field should be following format:

    sL.add_user(mk_token("Sakoh"))
    sL.add_user(mk_token("Sakoh"))

And, I think that the output format of former version of Overture Tools is

    sL.add_user(mk_token("Sakoh"))

style.

[Library4HoseiE_pure.pdf](https://github.com/overturetool/overture/files/349068/Library4HoseiE_pure.pdf)
[Library4HoseiE_pure.zip](https://github.com/overturetool/overture/files/349067/Library4HoseiE_pure.zip)

**Comment by nickbattle** [comment]
Traces used to hold the expansion of their arguments like this, but it leads to other problems with some values. For example, if the p1 argument is a token, then the "toString" of that values would give mk_token("Sakoh") as desired. But if the argument is an object, like "new A(p1)", then the toString of that object reference value would not be legal VDM - certainly not "new A(mk_token("Sakoh"))".

The code used to try to determine whether arguments could be directly represented or not. From memory, I think we recently decided to make all arguments symbolically represented, because of some other problem (which I can't recall!). But that does have the consequence you raise here.

One possibility would be for the trace expansion to show the variable bindings as well as the operation calls. For example, "let x = new A() in op(x)" expands to one test with two statements: first "x = new A()" and then "op(x)". Currently, the variable binding statements are not listed, but presumably that would be easy to change.

**Comment by nickbattle** [comment]
Incidentally, in VDMJ Test 16 says the following:
```
Test 16 = sL.add_user(mk_token("Sakoh")); sL.add_user(mk_token("Sakoh")); sL.add_book(mk_token("VDM_1")); sL.add_book(mk_token("VDM_1")); sL.borrow_book(mk_token("Sakoh"), mk_token("VDM_1")); sL.borrow_book(mk_token("Sakoh"), mk_token("VDM_1")); sL.getAttributes()
Result = [(), Error 4071: Precondition failure: pre_add_user in 'Library' (.\Library.vdmpp) at line 24:11, INCONCLUSIVE]
```

**Comment by shinsahara** [comment]
My code is following. So, p1, p2 are not objects, and there is no variables.

    T2:
    	let p1,p2 in set {mk_token("Sakoh"), mk_token("Larsen")} in 
    	let c1,c2 in set {mk_token("OO Construction_1"), mk_token("VDM_1")} in 
    		(sL.add_user(p1); sL.add_user(p2); 
    		 sL.add_book(c1); sL.add_book(c2); 
    		 sL.borrow_book(p1, c1); sL.borrow_book(p1, c2);  
    		 sL.getAttributes())

**Comment by nickbattle** [comment]
Yes Shin, so that is why VDMJ prints them out. But as I mentioned, there was some other problem that we were trying to avoid in Overture which caused us to remove the argument evaluation in trace expansions.

PJ, can you remember why we changed this?

**Comment by peterwvj** [comment]
This could be related to #557, which I think is a simplified version of one of the issues reported by Paul Chrisholm.

**Comment by peterwvj** [comment]
The changes made to the `TraceExpander` might be a clue https://github.com/overturetool/overture/commit/9f86979dcda80dd61b85546a99e603eb839e1d78

**Comment by nickbattle** [comment]
Ah yes, that's right. The comment is the clue:
```
// If the value includes mk_R() expressions, we may not be able to resolve the type,
// either because the type R is not explicit (like mk_M`R) or because the type may
// have been exported from its module as a "struct" and so mk_R(x) is not legal.
// Note that a RecordValue's toString does not explicitly expand the module name.
// So we exclude anything with mk_R expressions too...
```
Unfortunately, the test then looks for "mk_" in the toString of the value, which is catching Shin's mk_token as well. We could tighten that up, so that mk_token is allowed, but that would still leave us with a more general problem that records give us problems.

I'm not 100% sure, but I think the recent VDMJ changes to CT avoid this whole issue by distinguishing between the value in the test sequence (which isn't mucked about with) and the string appearance of the test (which can do anything it likes). There is an issue open to upgrade Overture's CT to use the new VDMJ algorithms, so this fix would be picked up then too.

**Comment by shinsahara** [comment]
I closed this by accident.
Do you know how to re-open?

**Comment by nickbattle** [comment]
Re-opening :-)

**Comment by shinsahara** [comment]
Thanks a lot :-)

**Comment by peterwvj** [comment]
Nick, so if I understand you correctly, you suggest that we change the `TraceExpander` check to something like

```Java
if ( !value.matches(".*mk_token\\(.*")) && value.matches(".*mk_\\w+\\(.*") )
{
  newargs.add(arg.clone()); // Give up!
}
```
This would fix Shin's issue, right?

**Comment by nickbattle** [comment]
Well, I think we mean "a single mk_token" is OK, and "any mk_Rs are not", which 
is slightly different? But something close to this, yes.

**Comment by peterwvj** [comment]
Thanks for your input Nick. I tried to tidy up the check and added a test to confirm that it works. Also, I confirmed that this did not re-introduce the #557 issue. Now Shin's test is reported as:

![ct-token-args](https://cloud.githubusercontent.com/assets/5388919/16710294/c884adee-4629-11e6-9f41-2413603fe816.png)

The fix is available on pvj/issue-578-ct. Do you agree (Shin, Nick) that this does it?

**Comment by nickbattle** [comment]
Looks OK to me - I think this was the intended outcome of the test (VDMJ does 
this, as I recall).

**Comment by shinsahara** [comment]
Hi Peter,

I think it's OK.
Thanks a lot.

**Comment by peterwvj** [comment]
Good - thanks for your input both of you.
