### ISSUE TITLE
VDMUtil`seq_of_char2val should handle nonsense conversions gracefully

### ISSUE THREAD

**Issue by kgpierce** [overturetool/overture#582]
The VDMUtil function seq_of_char2val[@p]:seq1 of char -> bool * [@p] should produce mk_(false, nil) if the parsed value is not of the type of @p.

The current behaviour is that if the string is a valid VDM type then it is returned, even if the type is not that of @p, which causes Overture to stop with a runtime conversion error. The attached model shows this behaviour.

[VDMUtilTest.zip](https://github.com/overturetool/overture/files/363796/VDMUtilTest.zip)

**Comment by nickbattle** [comment]
I think the second case, passing an empty string, should be a TC error, since the VDMUtil function is defined to take a seq1 of char. The probem is with the third case. This fails because the type conversion to "bool * [@P]" is not performed by the Java native code of the library, and is therefore outside of the catch block that is looking for conversion errors.

**Comment by nickbattle** [comment]
There is already some special case library code for IO`get_file_pos and IO`freadval. The former has to be clever to understand where it is being called from in the file, the latter is passed a full Context for the evaluation, so that it can refer to variables and type invariants when reading values (I think!). So we could create another special case for VDMUtil`seq_of_char2val, but they are obviously not ideal.

**Comment by peterwvj** [comment]
The conversion error occurs in `FunctionValue`, line 497:
```Java
 rv = body.apply(VdmRuntime.getExpressionEvaluator(), evalContext).convertTo(type.getResult(), evalContext);
```
From the evaluation context it should be possible to detect this special case, right?

**Comment by peterwvj** [comment]
I sort of like @tomooda suggestion

> One easy quick hack is to wrap by VDM if Java can't do that.
>
> seq_of_char2val0:seq1 of char -> bool * ?
> seq_of_char2val0(s) == is not yet specified
>
> seq_of_char2val[@p]:seq1 of char -> bool * [@p]
> seq_of_char2val(s) ==
>   let mk_(b, v) = seq_of_char2val0(s) in
>     if is_(v, @p) then mk_(b, v) else mk_(false, nil)
>   post let mk_(b,t) = RESULT in not b => t = nil;
>
> Then change the name of the Java method to seq_of_char2val0 and export
> only seq_of_char2val.
> 
> tomo

**Comment by kgpierce** [comment]
So Tomo's "hack" worked for my immediate problem and FMU generation :) It falls over with empty string since the type is seq1 of char. In my example the COE from INTO-CPS sends "", "[]" before "1", "2", ..., so the first few values are typically not of the right type and should be ignored. Changing the definitions to seq of char works fine. Is there a reason not to change it to seq of char for the library version?

**Comment by peterwvj** [comment]
I would have no problem with that since the function is intended to reject nonsense conversions anyway. Also, that change would be fully compatible with models that use the previous version of the library function. Other views on this?

**Comment by ldcouto** [comment]
I don't see any problems. Do we return `mk_(false, nil)` for empty strings?

**Comment by nickbattle** [comment]
The problem with empty string arguments, Luis, is that this is type checking error, since the function is currently defined to take a seq1 of char. Ken is asking whether it makes sense to change the function signature to seq of char so that blank strings are accepted (but return mk_(false, nil), as you say).

I'm sort-of-ok with this. It irks me that the function is clearly designed to evaluate arbitrary expression strings, and that an empty string is not a sensible input. But then these libraries are about "get things done" rather than "specify how things work", and I can see the practical argument for an empty string being a common input value (albeit an erroneous one). Would it make sense to loosen the type even more and make it [seq of char], so that you could pass nil? (If not, why not?)

**Comment by peterwvj** [comment]
I guess there's a practical argument to that too, yes.

**Comment by ldcouto** [comment]
Well, I was suggesting expanding the type signature and returning false for
empty strings. So... I guess we agree?

I can't immediately think of a scenario where you would pass nil.

**Comment by tomooda** [comment]
Accepting an empty string is ok. 
Emptiness can be check at the caller side (which is the most significant difference from the other cases that returns mk_(false, nil)), but I see the benefit of simplifying specs that use VDMUtil.

Accepting nil does not make sense to me. Nil is just a different beast.

**Comment by peterwvj** [comment]
I would be satisfied by simply changing the signature to `seq of char`. My main concern is the empty string case. Nick, can you think of a good example where `[seq of char]` is particularly helpful?

Another thing. Do you think that changing the signature needs to be taken to the Language Board?

**Comment by peterwvj** [comment]
I talked with Kenneth and he told me that they expect to release a new version of Crescendo soon. Since the feature requested in this issue is quite important to the Crescendo users I think it's important that we update the function to handle nonsense conversion in a better way. Unless there are any objections I would like to add the fix suggested by Tomo. I'm willing to take it a bit further and change the type of the input argument to `seq of char` but I'm not sure whether we can do this without raising the issue at the Language Board.

**Comment by peterwvj** [comment]
I updated the `VDMUtil` libraries (SL, PP, RT) to use the check suggested by Tomo.

So for your example the following model

```
class Conv

operations

public run: () ==> ()
run() == (
		let mk_(x,msg) = VDMUtil`seq_of_char2val[nat]("2") in 
			IO`printf("(%s,%s)\n", [x, msg]);
			
		let mk_(x,msg) = VDMUtil`seq_of_char2val[nat]("[]") in 
			IO`printf("(%s,%s)\n", [x, msg]);		
)

end Conv
```

...now produces 

```
(true,2)
(false,nil)
```

I decided *not* to change the type of the input argument to `seq of char` since I did not receive any input from anyone. Since this would require a change to the public interface of the `VDMUtil` class, I suggest we discuss it with the other LB members. When/if we implement it in the tool we can raise it as a separate issue. For now, I'll consider this issue closed. If you disagree, just open the issue.

As a side note I also had to update the `ide/help` plugin to use the newest version of the example packager. Otherwise all of the examples would not bundle with the new version of `VDMUtil`. See - https://github.com/overturetool/overture/commit/434165029ed762c7122e401f3a78c256cd715520
