### ISSUE TITLE
VDMUtil`seq_of_char2val cannot parse record type

### ISSUE THREAD

**Issue by kgpierce** [overturetool/overture#586]
When trying to parse a record, I get (false,nil). Consider the following:

```
class Test

types

Message :: x: int
           y: int
           z: int;

Tuple = nat * nat

operations

public run: () ==> ()
run() == (
        let mk_(x,msg) = VDMUtilDebug`seq_of_char2val[Message]("mk_Message(1, 2, 3)") in 
            IO`printf("(%s,%s)\n", [x, msg]);

        let mk_(x,msg) = VDMUtilDebug`seq_of_char2val[Tuple]("mk_(1,2)") in 
            IO`printf("(%s,%s)\n", [x, msg]);       

        let mk_(x,msg) = VDMUtilDebug`seq_of_char2val[seq of nat]("[]") in 
            IO`printf("(%s,%s)\n", [x, msg]);       
)

end Test
```

This produces the output:

```
(false,nil)
(true,mk_(1, 2))
(true,[])
```

From dumping the stack trace to console, it looks like something to do with checking the invariant: 

```
org.overture.interpreter.assistant.type.SInvariantTypeAssistantInterpreter.getInvariant(SInvariantTypeAssistantInterpreter.java:25)
org.overture.interpreter.values.RecordValue.<init>(RecordValue.java:50)
org.overture.interpreter.eval.ExpressionEvaluator.caseAMkTypeExp(ExpressionEvaluator.java:1078)
org.overture.interpreter.eval.ExpressionEvaluator.caseAMkTypeExp(ExpressionEvaluator.java:123)
org.overture.ast.expressions.AMkTypeExp.apply(AMkTypeExp.java:386)
VDMUtilDebug.seq_of_char2val0(VDMUtilDebug.java:80)
...
```

Adding an invariant to the type did not seem to improve the situation. Adding an invariant to the Tuple type works fine. Model attached for testing  purposes.

[VDMUtilTest.zip](https://github.com/overturetool/overture/files/376543/VDMUtilTest.zip)

**Comment by nickbattle** [comment]
This is a similar cause to #582. The native function does not have access to either the runtime context of the spec, nor the definition Environment, so it cannot determine the type of the mk_Message. This leads to a null type field, and the stack trace indicates that it fails while trying to check whether the (null) type has an invariant that it has to honour.

We discussed (emali?) various ways of getting a Context or Environment through to the native library so that it can perform a type check or type conversion to the polymorphic target type. But there is also a more subtle question of what the Environment should be when the code tries to evaluate an expression. For example, should the default class/module be that of the caller?

The approach we took in IO'freadval (which is very similar) was to make the default module "IO". That means that your mk_Message string would fail to type check, requiring mk_A'Message instead.

**Comment by kgpierce** [comment]
Ah yes, that makes sense. In this case Tomo's fix does not help, though tuples work okay so one can deconstruct and reconstruct records at the either end if required.

It would be nice to fix this somehow. I think the previous discussions were on email, which we could copy here. My own feeling was that it would be good if the context in the external Java was the same of where the call was made. Otherwise I'm not against having to fully qualify types, as long as this is explained somewhere (including perhaps comments in the VDM classes of the VDMUtil).

**Comment by kgpierce** [comment]
Actually I think the discussion is in #582.

**Comment by peterwvj** [comment]
For consistency we should probably make  `seq_of_char2val` behave in a way similar to that of `freadval`

I don't think it's a big deal that the user must specify the fully qualified name of the type as long as this is made clear in the documentation (the javadoc). Probably it's not :) so if we decide to do something similar as we did for `freadval` then we should probably update the documentation of the function.

Looking at the interpreter implementation of `freadval` it seems fairly straight-forward to set the default module.

**Comment by peterwvj** [comment]
In 2.3.8 it seems to be setting the default module to `VDMUtil` - see

```Java
public static Value seq_of_char2val(Value arg)
{
  ValueList result = new ValueList();

  try
  {
    SeqValue seq = (SeqValue) arg.deref();
    StringBuilder expression = new StringBuilder();

    for (Value v : seq.values)
    {
      CharacterValue ch = (CharacterValue) v.deref();
      expression.append(ch.unicode);
    }

    LexTokenReader ltr = new LexTokenReader(expression.toString(), Dialect.VDM_PP);
    ExpressionReader reader = new ExpressionReader(ltr);
    // Set current module
    reader.setCurrentModule("VDMUtil");
    PExp exp = reader.readExpression();
    result.add(new BooleanValue(true));
    Context ctxt = new Context(Interpreter.getInstance().getAssistantFactory(), null, "seq_of_char2val", null);
    ctxt.setThreadState(null, null);
    result.add(exp.apply(VdmRuntime.getExpressionEvaluator(), ctxt));
  } catch (Exception e)
  {
    result = new ValueList();
    result.add(new BooleanValue(false));
    result.add(new NilValue());
  }

  return new TupleValue(result);
}

```
However, I can't convert the string to a ASCII value:
```
class Conv

types

public Message :: x: int
           y: int
           z: int;

Tuple = nat * nat

operations

public run: () ==> ()
run() ==
let mk_(x,msg) = VDMUtil`seq_of_char2val[Conv`Message]("mk_Conv`Message(1, 2, 3)") in 
  IO`printf("(%s,%s)\n", [x, msg]);

end Conv
```

```
**
** Overture Console
**
(false,nil)

new Conv().run() = ()
```

Should this not be working?

**Comment by kgpierce** [comment]
I didn't have any luck either putting the Message type in the VDMUtil class, even fully qualified. The stack trace always has the same as above.

**Comment by nickbattle** [comment]
The Conv example above is failing because VDMUtil does not type check the expression that it parses from the argument string passed, and that then fails to find a PType value in the AST when the expression is evaluated. Adding a couple of lines (taken from IO.java) seems to fix this. I'll check in that change. (Though the function in my VDMUtil is called seq_of_char2val_, with an underscore?)
```
> p new Conv().run()
(true,mk_Conv`Message(1, 2, 3))
```

**Comment by peterwvj** [comment]
Sounds good. Regarding the underscore. Note that there are two versions of `seq_of_char2val` - one of them acts as a "wrapper". It was introduced to deal with non-sense conversions - see comment https://github.com/overturetool/overture/issues/582#issuecomment-232774385
