### ISSUE TITLE
Parser allows multiple consecutive access modifiers for functional descriptions

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#610]
The parser accepts a function or operation that includes multiple consecutive access modifiers. One way to demonstrate this is using the function below:

```
class A

functions

private
protected
public
f: () -> nat
f() == 1;

end A
```

```
λ java -jar Overture-2.4.3-SNAPSHOT.jar -vdmpp A.vdmpp 
Parsed 1 class in 0.058 secs. No syntax errors
Type checked 1 class in 0.078 secs. No type errors
```

VDMJ responds similarly.

**Comment by nickbattle** [comment]
LOL, nice one. I think we should declare it as a new language feature :)

(Should be a simple fix, I'll take a look when I get a minute).

**Comment by nickbattle** [comment]
The bug is in DefinitionReader, readAccessSpecifier (naturally). You'll see it loops checking for the various types of specifier, as they can occur in any order. But it doesn't check whether it already has one of any particular type. So you could probably have "static static pure pure" as well.

Although this is obviously a mistake, it should be clearer in the grammar too - the LRM I have lists an "access operation definition" as two (and only two) orderings of the keywords. This made sense when it could only be either static or an access specifier, but with pure and async in the mix we have various possibilities, and picking two arbitrary orderings seems strange:
```
access operation definition = ( [ ‘pure’ ], [ ‘async’ ] [ access ], [ ‘static’ ]) |
( [ ‘pure’ ], [ ‘async’ ] [ ‘static’ ], [ access ]),
operation definition ;

access = ‘public’ | ‘private’ | ‘protected’ ;
```

**Comment by nickbattle** [comment]
I've pushed a fix for this to ncb/development. I've not done anything about the LRM grammar though.

**Comment by peterwvj** [comment]
That's great thanks! I think it's fine to consider this issue closed now that the tool issues have been dealt with. However, I'll raise an issue in the documentation repository so we don't forget to clarify the grammar.
