### ISSUE TITLE
Errors with VDM++ trace example

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#628]
Philippe de Rochambeau created a traces specification that fails with Overture 2.4.6. The patch attached seems to fix the problem, but the existence of the "if (!failed)" test in the Interpreter is very worrying! This makes no sense. Perhaps the traces in the Eclipse UI are not using this code? I tested it with command line Overture in effect. If that is the explanation, the patch is probably a fix (and does seem to work). The new traces in VDMJ4 work fine.

[test.vpp.txt](https://github.com/overturetool/overture/files/1050557/test.vpp.txt)
[traces.patch.txt](https://github.com/overturetool/overture/files/1050559/traces.patch.txt)

**Comment by nickbattle** [comment]
Without the patch, I get a class cast exception (missing deref in TraceVariablesList) and then, if that is fixed, an index out of range exception (Interpreter runtraces is skipping things after the first error??).

**Comment by peterwvj** [comment]
Thanks for reporting. I'll take a look.

**Comment by peterwvj** [comment]
I'm assuming that the index out of bounds exception that you get is raised immediately after the tests start executing - am I right? When I apply your patch and let the tests run for a long time the index out of bounds exception is never raised. I stopped at test 192425. Here's how I build the CLI:

- Apply patch
- `cd <oveture-repo-root>/core`
- Run `mvn clean install -DskipTests -Dmaven.javadoc.skip=true` in order to generate`<oveture-repo-root>/core/commandline/target/Overture-2.4.9-SNAPSHOT.jar`
- Launch the interpreter: `java -jar Overture-2.4.9-SNAPSHOT.jar -vdmpp test.vdmpp -i`
- Run the trace: `runtrace T combiTesting0`.

Are you sure you build the CLI? If yes, can you show me the steps that produce the error?

**Comment by peterwvj** [comment]
To me it looks like the patch fixes the problem. I built a development version of Overture that contains the fix. Try to reduce the range from `{1,10}` to (say) `{1,3}` and you should see it working. You can download it here:

http://overture.au.dk/overture/test/Build-119_2017-06-08_08-44/
