### ISSUE TITLE
Launch configuration entry point with parameters problem

### ISSUE THREAD

**Issue by idhugo** [overturetool/overture#629]
A student reported an not understandable error message while launching a configuration in the Overture IDE. The problem can be demonstrated using the following model:

```
class A

operations

public A : nat ==> A
A (x) == skip;

public op : () ==> ()
op () == skip;

end A
```

When the launch configuration, as defined in the screenshot below, is executed:

![screenshot from 2017-06-07 15 51 21](https://user-images.githubusercontent.com/13678823/26881933-36b126ba-4b99-11e7-8fbc-5fafce83ed11.png)

.. the following error is shown:
```
Initialization: java.lang.Exception: Class A(5) not loaded
java.lang.Exception: Class A(5) not loaded
	at org.overture.interpreter.runtime.ClassInterpreter.setDefaultName(ClassInterpreter.java:134)
	at org.overture.interpreter.debug.DBGPReaderV2.main(DBGPReaderV2.java:527)
```
Presumably, the IDE wrongfully confused the Class (as specified in the launch configuration) with the class name.

**Comment by nickbattle** [comment]
I noticed something very similar recently. I concluded that Overture would not use anything other than the default constructor in the "Class" field, so if you put "A(5)", it is looking for that whole string as a class name to create the instance. The only launchers I can get working use the bare class name, or the name followed by "()" in the "Class" field, which would use "A()" to create the instance.

Since the "Search" button will populate the Class field with (say) "A(nat)", this clearly indicates that you should be able to use arbitrary constructors.

**Comment by peterwvj** [comment]
Based on the error message it sounds like the class name is "parsed" in a very naive way (like Nick suggests). I'll try to take a look at it some time this week.

**Comment by peterwvj** [comment]
So as we expected, this problem is caused by the "Class" text field being "parsed" in a way that only works for default constructor calls. To improve this, I changed the `AbstractVdmMainLaunchConfigurationTab` to parse this text field using the expression reader. In that way, the class name (or module name, if you prefer) can be found using a visitor (rather than using String manipulation). Based on the testing I've done so far this fix seems to work. In particular, if you run the launch configuration shown above, Overture now outputs the following:

```
**
** Overture Console
**

new A(5).op() = ()
Executed in 0.044 secs. 
```

Still, we should be careful with changing launch configuration related code (IDE stuff). It's not easy to test.

I've built a development version of Overture that contains the fix. Could you please try it and let me know if everything works as expected? You'll find it here:

http://overture.au.dk/overture/test/Build-118_2017-06-07_20-42/

**Comment by idhugo** [comment]
Tried the linux 64 version. Working good!

**Comment by peterwvj** [comment]
Very good. Thanks for testing. I'll merge it into `development`.
