### ISSUE TITLE
Type visibility error not reported

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#631]
In some situation the type-checker does not detect when the visibility of a parameter is less than that of its operation. This issue can  be demonstrated using the following example:

```
class A

types

T = nat;

operations

public static op : (T * nat) ==> () 
op(x) == is not yet specified;

end A
```

For this example, one would expect the following error to be reported

```
Error 3028: Operation parameter visibility less than operation definition in ....
```

... however, currently Overture reports no type errors. It seems to be related to the fact the parameter type is wrapped in brackets.

**Comment by nickbattle** [comment]
I think the problem is that the NarrowerThanComparator does not have an entry specified for a ProductType. It's not the brackets as such. That's just a guess, comparing what VDMJ does with Overture's visitor.

**Comment by nickbattle** [comment]
Yes, your spec gives the error expected if you add this method:
```
	@Override
	public Boolean caseAProductType(AProductType type,
			AAccessSpecifierAccessSpecifier accessSpecifier)
			throws AnalysisException
	{
		for (PType t : type.getTypes())
		{
			if (t.apply(this, accessSpecifier))
			{
				return true;
			}
		}

		return false;
	}
```
I'd push the fix, but I'm on the eq-od branch at the moment and a bit pushed for time :)

**Comment by nickbattle** [comment]
PS. It's a slightly unusual case. If an operation is "T * T ==> T", there are no product types involved, even though the parameters are clearly intended to represent the product of the two. But if you put brackets around the two types, "(T * T) ==> T", then there is only one parameter type, which is definitely a product. Since we were missing the product method in the narrower-comparator, the first example worked, but the second fails - not because of the brackets as such, but because they reveal the missing product method :-)

**Comment by peterwvj** [comment]
Very good, thanks! I'll add the missing method, including the test.

**Comment by peterwvj** [comment]
Okay it's fixed in `pvj/main`.
