### ISSUE TITLE
Make Overture and Language Syntax Consistent

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#632]
According to the module syntax, sequences of imports or exports (types/values/functions) must be separated by semi-colons. Overture is more lenient in that it does not require the semi-colons, though does support them.

Overture and the language syntax should be consistent. If Overture is made more strict it would break some specifications, though they are easily corrected. If the language syntax is made more lenient, for `import types signature` the syntax (A.1.1) would change from

`import types signature = ‘types’, type import, {‘;’, type import}, [‘;’] ;
`

to

`import types signature = ‘types’, type import, [‘;’], {type import, [‘;’]} ;
`

Similar for `import values signature`, `import functions signature`, `import operstions signature`, `export types signature`, `export values signature`, `export functions signature` and `export operstions signature`.

**Comment by nickbattle** [comment]
This issue was effectively solved by the addition of the -strict flag - that is, give warnings when Overture specs are not strictly conformant to the LRM. I think we currently default to not-strict, but that is a different question; we have the capability to advise the user of these problems. Closing.
