### ISSUE TITLE
The Quick Interpreter gives a "null" in the message

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#656]
### Description

The Quick Interpreter gives a "null" in the message if you evaluate something like "1 +" (without the quotes)

### Steps to Reproduce

1. Evaluate "1+" (without the quotes) in the quick interpreter

**Expected behavior:**

A meaningful (parse) error should be printed.

**Actual behavior:**

The quick interpreter reports.

```
Error 2034: Unexpected token in expression: null in 'DEFAULT' (console) at line 2:0
```

The message should be something more meaningful than "null".

**Reproduces how often:**

Every time.

### Versions

- Overture 2.5.2
- Ubuntu 17.04 (64 bit)
- OpenJDK 1.8.0_0151 (64 bit)

**Comment by nickbattle** [comment]
This was because the VDMToken for EOF had a "null" display string - thinking that it would never be used. But when you parse "1 +", then token location of the error is EOF. So I've made the display string for EOF be "EOF". I haven't built a full tool, but this fixes the problem on the command line (which was showing the same behaviour).

Now pushed to ncb/development.

**Comment by nickbattle** [comment]
OK, I built a version with this included, and it's fine:
```
1+ = Error 2034: Unexpected token in expression: EOF in 'DEFAULT' (console) at line 2:0
```
