### ISSUE TITLE
Type checker fails to identify invalid type

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#658]
### Description

The following module type checks successfully. 
```
module Issue
exports all
definitions

functions

  f: nat -> nat
  f(a) == if a=0 then 0 else [];

end Issue
```
### Steps to Reproduce

1. Load the above module into Overture.

**Expected behavior:** Type checking error reported.

**Actual behavior:** Module type checks successfully.

**Reproduces how often:** Always.

### Versions

Overture 2.5.6
macOS 10.13.2

### Additional Information

None.

**Comment by nickbattle** [comment]
So in this case, the type of the expression body is "nat | seq of ?" which is compatible with the return type - ie. it is possible that the spec is correct, and the typechecker uses possible semantics. Having said that, VDMTools does complain about this (says the else clause is the wrong type), and there are other circumstances where VDMJ/Overture also insists that all branches of an evaluation are type compatible with the expected type.

I'll have a look at where VDMJ does enforce the type and we can try to decide when possible semantics should apply and when not.

**Comment by nickbattle** [comment]
Then again, sometimes there are just bugs :-)  The type checking of sequences was very carefully checking that the elements of the sequence correspond to the constraint, but didn't check at the end that the overall sequence was compatible - ie. here didn't check that [] is a nat.

I'll make that change, but it's mucking up some of the tests which always takes a while to sort out.

**Comment by nickbattle** [comment]
This turns out to be more complicated that I'd thought. After fixing the problem above (which reveals the problem in the example given) some of the tests fail, like this:
```
values
  L : seq of char | seq of int = [ if true then 3 else 'b' ];
```
Currently, the type of the sequence on the RHS is inferred as "seq of (nat1 | char)". So when the expected type of "seq of char | seq of int" is propagated in and (now) tested, it fails - since "seq of (nat1 ! char)" is not a subtype of the expected type.

The problem may be that the test for subtype membership is too strict. Or the problem may be that the inferred type is using an "inclusive or" of the member types, when in fact this ought to be an "exclusive or" - ie. the inferred type should be "seq of char | seq of nat1" since the "if" expression is clearly either one or the other, not "both".

Either way, I need to do some thinking! So I can't apply the simple fix above quickly.

**Comment by nickbattle** [comment]
OK, I think the easiest thing to do is to make a more relaxed type check, using possible semantics rather than subtyping - this is what other similar constructs do in the type checker. I'll push the fix to ncb/development, assuming this isn't causing serious problems.

**Comment by pglvdm** [comment]
I believe that the way to solve this from a type checking perspective is to operate with a check that both the then expression as well as the else expression should be of the "expected type". In VDMTools this was established using a MergeTypes in the TCAUX module (see https://github.com/vdmtools/vdmtools/blob/master/spec/ss-spec/tcaux.vdm). So one needs to operate always with a notion of what is expected type of an expression (downwards) as well as deriving the actual type (upwards) and in case there is no overlap for one path through a model an error should be reported.

**Comment by nickbattle** [comment]
That is basically how VDMJ works now, Peter. The problem here was that the "downwards" check was not being performed for seq/set/map enumerations at the level of the whole seq/set/map - it was correctly checking that the elements of the seq/set and dom/rng of the map were correct, but not checking the overall type. Just a bug :-)
