### ISSUE TITLE
Issue in sequence comprehension

### ISSUE THREAD

**Issue by olafur-skulason** [overturetool/overture#692]
### Description

When attempting to use sequence comprehension with multiple variable bindings, I get a compiler error. The form I am using matches the way shown in the language manual chapter 6.8 Sequence Expressions the syntax should be:

sequence_comprehensionp = [ expression | bind_list ...

if we jump to bind_list you are allowed to use multiple binds, seperated by a comma (',').

### Steps to Reproduce

class error_description
types

operations

output: () ==> seq of (nat*nat)
output() ==
let x = [mk_(a,b) | a in set {1,2}, b in set{3,4}] in x;

end error_description

In txt because vdmpp is not a valid file ending.
[error_description.txt](https://github.com/overturetool/overture/files/2565534/error_description.txt)

**Expected behavior:** A sequence with a single element of the tuple

**Actual behavior:** Compiler error : Expecting ']' after list comprehension.

**Reproduces how often:** Always

### Versions

Which version of Overture are you using? Also, please include the OS and what version of the OS you're running.

Overture 2.6.2
Ubuntu 18.04

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nickbattle** [comment]
A sequence comprehension must define the order that the elements (from the binding) occur in the result. This is different to a set comprehension, where there is no order. So if a sequence comprehension is driven by a set binding, there can only be one, it must bind a single variable, and that variable must be of a type that is ordered. If a sequence comprehension is driven by a sequence binding, the order is implicit in the bind value and so multiple variables can be bound, but you can still only have one binding, so that the order is defined.

So the error above is because the parser expects to see the end of the comprehension after the first set bind, ie. "]". It is confusing because it says "after list comprehension"; it would be better if it said "after set bind", but at least the character position is correct: position 35 is the comma after the bind.

Put another way, what order did you expect the sequence to be in? If it does not matter, you can convert this to a set comprehension (which can use multiple binds), and then use set2seq.
```
operations
output: () ==> seq of (nat*nat)
output() ==
        let x = set2seq[nat * nat]({mk_(a,b) | a in set {1,2}, b in set{3,4}}) in return x;

functions
        set2seq[@T]: set of @T -> seq of @T
        set2seq(a) ==
                if card a = 0
                then []
                else let e in set a in
                        [e] ^ set2seq[@T](a \ {e})
        post elems RESULT = a and len RESULT = card a
        measure card a;

> p output()
= [mk_(1, 3), mk_(1, 4), mk_(2, 3), mk_(2, 4)]
Executed in 0.017 secs. 
```

**Comment by nickbattle** [comment]
No! My mistake - gosh this is confusing :-)  The sequence bind can bind multiple variables, but it can only do so via a simple bind, so that the sequence is defined. So for example, you can say:
```
[ a+b | mk_(a, b) in seq [...] ]
```
But you cannot say:
```
[ a+b | a, b in seq [...] ]
```
Because in the 2nd case, you don't know the ordering of the a/b pairs from the sequence. In the first case, they are defined to come in pairs taken from each sequence value.

So the LRM is still wrong. Sorry for the confusion.

**Comment by olafur-skulason** [comment]
Thank you nickbattle, for the quick response.

I was attempting to use multiple bind to generate record type traces, so I was not thinking too much about the actual order (since I wanted all of them). I did work around the issue, by simply using multiple binding operations and creating the record just before passing it into the operation. 

I wasn't sure if it was an oversight in the compiler, or an error in the Language Manual.

Thank you for looking into it.

**Comment by peterwvj** [comment]
Let's propose a change and deal with the LaTeX stuff later. Really we should close this issue (it's not a tool issue) and open a new one in the documentation repository.

**Comment by nickbattle** [comment]
Yes, as PJ says, we should raise a doc issue. The LB will then catch that when the LRM is next updated. I can record the change needed in that new issue.

**Comment by peterwvj** [comment]
Closing this issue in favor of https://github.com/overturetool/documentation/issues/17

**Comment by peterwvj** [comment]
FYI, the Language Reference Manual has now been corrected.

**Comment by nickbattle** [comment]
I'm re-opening this to commit some changes in light of a recent issue. The proposed LRM change said that sequence comprehensions could use set or seq binds, but in fact there is no reason why they cannot use type binds, as long as the type being bound is ordered. Both VDMJ and Overture were treating type binds as a parse error - ie. agreeing with the LRM, as they should. But I think the LRM is wrong.

I've also re-opened documentation bug 17, to allow the LRM to be fixed.

**Comment by nickbattle** [comment]
Now fixed in ncb/development.

**Comment by idhugo** [comment]
Merged into development.
