### ISSUE TITLE
Type checker: reachable statement reported as unreachable

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#696]
### Description

Reachable return statement reported as unreachable.

### Steps to Reproduce

1. Create file bug.vdmsl with the following content

```
operations

op : seq of nat ==> nat
op (r) ==
(
  for y in r do return y;
  return 42; -- Warning 5006: Statement will not be reached in 'DEFAULT'
);
```

2. Load bug.vdmsl and evaluate `op([])`:

```
λ java -jar Overture-2.6.4.jar -vdmsl bug.vdmsl -i
Parsed 1 module in 0.044 secs. No syntax errors
Warning 5006: Statement will not be reached in 'DEFAULT' (bug.vdmsl) at line 7:3
Type checked 1 module in 0.046 secs. No type errors and 1 warning
Initialized 1 module in 0.035 secs. 
Interpreter started
> p op([])
= 42
Executed in 0.022 secs. 

```

**Expected behavior:**

Expected return statement not to be reported as unreachable.

**Actual behavior:** [What actually happens]

Return statement is reported as unreachable.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

Overture 2.6.4.

### Additional Information

The problem is the same for VDMJ.

**Comment by nickbattle** [comment]
Ah yes, of course it processes the body of the for-loop assuming that it will be executed, but if the sequence or set driving it is empty (or, presumably, if the "for x=here to there" form has here>there), then the body is only conditionally executed.

Should be an easy fix.

**Comment by nickbattle** [comment]
Statements are considered reachable when previous statements (even possibly) return a void type (the "()" type, returned by skip etc). If there is a void from a previous statement, then you can be reached; if not, the previous statement must have returned that value.

So naively, we can change for-loops to return a union of whatever their body returns and void, since the body may not be executed. But that then means that a for loop comprising just a return statement may not return, which causes several test specs that have such operations to throw a new error - because you cannot have a void return path from an operation body unless the return type is void.

For example, if we take out the 42 return from your example, with the "voidable forloops" tweak, you get:
```
Parsed 1 module in 0.054 secs. No syntax errors
Error 3313: Operation returns void value in 'DEFAULT' (test.vdm) at line 3:1
Actual: (() | nat)
Expected: nat
Type checked 1 module in 0.048 secs. Found 1 type error
Bye
```
So in a sense this is right: the for loop can skip and drop out of the operation. But I suspect there are a lot of operations out there which will fail if we make this change... maybe?

There is also a related point that for-loops that have sets/sequences that are definitely non-empty are not detected as such. So `for x in {1,2,3} do ...` will definitely execute the body, and so the void return is not needed. But in general, we cannot know whether a set/seq is empty statically.

Tricky to get this right. Any thoughts?

**Comment by nickbattle** [comment]
Thinking about Leo's recent problem with seq and seq1 checks, perhaps what is really needed here is to only return the void for cases of seq/sets - ie. we know that seq1/set1 driven loops **will** enter the loop. I'll try adding that and see how many tests break!

**Comment by nickbattle** [comment]
OK, that improves things considerably. There are now a couple of cases where the tests still fail. Firstly, RobotRT, which has the following operation:
```
public GetNextPoint : set of Grid`Point * Grid`Point ==> [Grid`Point]
 GetNextPoint(neighbours, dest) ==
   let tmp={p| p in set neighbours 
             & not exists q in set neighbours & 
                      Distance(p, dest) > Distance(q, dest)}
    in
      for all p in set tmp      
        do
        (
           WaitForAvalibility(p);
            return p
        )
pre card neighbours > 0;
```
TC can't determine that the set comprehension is a set1, because in general it cannot know that the predicate is ever true. Though clearly here the precondition and predicate mean that tmp will be a set1. So tweaking the spec to say `let tmp:set1 of Grid'Point...` fixes the problem.

That then just leaves various "external" tests that fail, which are all of the form:
```
  IndexForLoop2: real ==> real
  IndexForLoop2(a) ==
    for id = a to 2 * 9 do
      return id;
```
This returns a void type if a > 18, so it is a genuine error. But there are simpler specs (`for x=a to b`) which would also fail where we cannot know statically whether the for loop will be entered or not. These specs are possibly correct.

So I think we should fix this for the set/sequence loop statements, **not** fix it for the from/to loop cases, and adjust the remaining tests that fail to make them type clean.

Does that sound about right?

**Comment by peterwvj** [comment]
Thanks a lot for looking into this, Nick.

> So I think we should fix this for the set/sequence loop statements, not fix it for the from/to loop cases, and adjust the remaining tests that fail to make them type clean.

So fixing the RobotRT example requires changing the example in the documentation repository and then updating the corresponding submodule in the tool repository to point to the new example.

The external test results we can just override, I guess.

Should I go ahead and update the RobotRT example?

**Comment by nickbattle** [comment]
Yes, if you could update the external doc repo, then I can fix the corresponding results files. It may mean that we have a broken build for a while? Alternatively, I could send you a diff of the changes for the loop typecheck (pretty small) and you could apply/test everything in one go?

**Comment by peterwvj** [comment]
Yes, that would work! Preferably, you can push your TC changes to a branch (say ncb/issue-696) and then I can pick up your work from there.

**Comment by nickbattle** [comment]
OK, new branch ncb/issue-696 contains the changes I was testing with. You'll see it just affects the statement type checker, though I also tweaked RobotRT on the branch too.

**Comment by peterwvj** [comment]
Thanks, @nickbattle ! When I was trying to update the test results I found another problem in `pop3test.vdmpp`, line 217:

```
thread
  for cmd in cmds do -- Thread statement/operation must not return a value in POP3TestSender
    SendCmd(mc, cmd);
```

So it seems like the check is too strict.

**Comment by peterwvj** [comment]
Here's a minimal example:

```
class A
operations

public op : () ==> nat
op () == return 1;

thread

for - in [1,2,3] do
  op();

end A
```

**Comment by nickbattle** [comment]
I noticed this too - when I was making the same changes to VDMJ. I didn't think about it very hard and changed the cmds sequence to a seq1, thinking that it just meant that there must be at least one command to execute. But it can't be that simple because it's complaining that a value is returned, not that no value is returned (though changing it to seq1 does fix the error).

I'll take a look. It may be that the test of the thread return value is too strict somehow (though it ought to be a union of () and (), which should be () so... strange).

**Comment by nickbattle** [comment]
OK, the problem was that the for-loop return was adding a void to a union even if the return type was already void, and the thread check was looking for a void (not a union that contains a void). So now the for-loop checks test for void first before adding one. I think the minimal test is this:
```
class POP3TestSender
instance variables
	cmds : seq of nat;

operations
	SendCmd: nat * nat ==> ()
	SendCmd(mc, cmd) == skip;

thread
	for cmd in cmds do
		SendCmd(0, cmd)

end POP3TestSender
```
So that now works on the ncb/issue-696 branch.

**Comment by peterwvj** [comment]
Great! Thanks, Nick. In addition to the TC fixes, the pvj/main branch now has the updated test results files and bundles the new RobotRT example.
