### ISSUE TITLE
Launch configuration Interpreter tab's checkboxes are negated before calling the interpreter

### ISSUE THREAD

**Issue by idhugoid** [overturetool/overture#737]
### Description

The checkboxes settings are passed to VDMJ in case the option is unchecked... 

The solution is to remove the negation on the conditions in the file:

ide/debug/src/main/java/org/overture/ide/debug/core/launching/VdmLaunchConfigurationDelegate.java

**Comment by nickbattle** [comment]
Do you mean things like the precondition checks and measures? I'm *sure* I checked these (at some point) during the RC tests, and they were fine - there's a test for this in the list of things to check for a release.

**Comment by idhugoid** [comment]
Hi Nick. This issue appeared when I was adding the -strict flag feature. 

In my understanding, I was assuming that if I pass -strict to the interpreter, then in DBGPReaderV2 this is passed to the type-checker...  So I assumed I could just copy&refactor the "inv" checkbox setting (VdmLaunchConfigurationDelegate l224). 

It came out as a surprise, that when the checkbox is set we do not pass it as an command line argument to the interpreter...

And in the DBGPReaderV2 l263 we set it to false, in case we had passed it to the command line:
			} else if (arg.equals("-inv"))
			{
				Settings.invchecks = false;

This was late in the day and my time had elapsed, so I decided to open the issue to have a better look at it, and to understand well the logic. Is this the case in VDMJ command line? Adding -inv removes invariant checking?

**Comment by nickbattle** [comment]
Ah yes, OK I can see the issue. The VDMJ flags on the launch "Runtime" tab and VDMJ are "disable" flags, so if you pass `-pre` to VDMJ that disables precondition checking etc. When I was testing it, I read it that way and didn't notice. But as you say, the `-strict` flag has a positive sense, so that would be different to the others.

We should be careful here. If you make a change and release it, we need to (maybe?) tell users that all of their launch configurations need to be "inverted", otherwise they will be running without a load of checks. That would be a big problem!! Can we internally invert the settings - so that any previous settings are honoured, but they just "look different".

Another thought: are you adding `-strict` to the launch dialog, or to the project configuration? I think this belongs in the latter because this affects the type checking (as you save), regardless of how many launchers you have. Perhaps I just misunderstood and you raised this having noticed something about the launcher, but you're not changing the launchers?

**Comment by idhugoid** [comment]
Hi Nick,

I did not change and, preferably, would like to avoid to change any of the previous logic regarding the "inv" and the previous checks, because of the problems you rightly state.

I will close this issue then, now that I understand better. I will look into the type checker invocation issue in the rightful issue #732.
