### ISSUE TITLE
Returned higher order functions change behavior as a model is executed

### ISSUE THREAD

**Issue by JaScMiller** [overturetool/overture#739]
### Description

A higher order function returned from another function (via lambda syntax) will change behavior if that second function is called again. A function's behavior should not change each time the function is used. An example of this is attached by image and code.

### Steps to Reproduce

1. Create a function that uses its arguments to return another using lambda syntax.
2. Call this first function several times using different arguments.
3. Launch/execute the model using the console.
3. Notice how the returned higher order functions are behaving differently as expected.
4. See the example in image and code below.

```
module testing

definitions

	values
	
		should_be_true_1 = any_string_predicate({ string_equals_abc, string_equals_xyz })("abc"); -- Evals True
		should_be_true_2 = any_string_predicate({ string_equals_xyz, string_equals_abc })("abc"); -- Evals True
		should_be_true_3 = create_string_equals_function("abc")("abc"); -- Evals true
		should_be_false_1 = create_string_equals_function("xyz")("abc"); -- Evals false
		should_be_true_4 = any_string_predicate({ create_string_equals_function("abc"), create_string_equals_function("xyz") })("abc"); -- Evals True
		should_be_true_5 = any_string_predicate({ create_string_equals_function("xyz"), create_string_equals_function("abc") })("abc"); -- Evals false
		

	functions
	
		string_equals_abc: seq of char -> bool
		string_equals_abc(str) ==
			str = "abc"
		;
		
		string_equals_xyz: seq of char -> bool
		string_equals_xyz(str) ==
			str = "xyz"
		;
	
		create_string_equals_function: seq of char -> (seq of char -> bool)
		create_string_equals_function(str) ==
			lambda x: seq of char & x = str
		;
	
		any_string_predicate: set of (seq of char -> bool) -> (seq of char -> bool)
		any_string_predicate(predicates) ==
			lambda x: seq of char &
				exists r in set { predicate(x) | predicate in set predicates } & r
		;

end testing
```

![Capture](https://user-images.githubusercontent.com/44124059/93565725-bcb17580-f983-11ea-81d0-1ef993576918.PNG)

**Expected behavior:** When a higher order function is returned as a lambda, then it should be consistent everytime it is called.

**Actual behavior:** When a higher order function is returned as a lambda, it's behavior can vary if the producing function is called again.

**Reproduces how often:** Reliably able to reproduce 100% of the time.

### Versions

Running version 2.7.4 with Windows 10

### Additional Information

Was trying to build some combinatorial/functional parsing in VDM-SL and found this. Obviously anything such as this which relies heavily on higher order functions is hard to do with this issue.

Similar problem when a lambda makes use of a recursive function under similar circumstances, an error indicating that the measure of the recursive function has been violated can sometimes show up even if it hasn't been the case, as another lambda from the same producing function is interferring.

**Comment by nickbattle** [comment]
Thanks for reporting this. I'll have a look over the weekend, but as you say functions should always return the same values, given the same arguments.

**Comment by nickbattle** [comment]
OK... I have had a very quick look at this, and I think I see a big clue about what might be going on. You're creating a set of functions as part of the bind within the exists clause. To create a set, the runtime has to determine whether two functions are "equal", and in general this is a difficult thing to do(!). What the runtime actually does is to compare the type signature and the toString of the two function values; if these are both identical, the functions are deemed equal, else they are not equal.

That may be part of the issue here, but I'm not certain that it explains it completely. I'll have a closer look when I get time.

**Comment by tomooda** [comment]
Nick, I think it's caused by equality between functions.
```
> print card {create_string_equals_function("abc"), create_string_equals_function("xyz")}
1
```

**Comment by tomooda** [comment]
Sorry, my reply was redundant.

**Comment by JaScMiller** [comment]
Ah I see, sorry I do not have a great understanding of Overture under the hood, but a little investigation shows this might be the case. For example I define the following function:

```
any_string_predicate_2: (seq of char -> bool) * (seq of char -> bool) -> (seq of char -> bool)
		any_string_predicate_2(predicate1, predicate2) ==
			lambda x: seq of char &
				predicate1(x) or predicate2(x)
		;
```

And then run this:

```
print any_string_predicate_2(create_string_equals_function("xyz"), create_string_equals_function("abc"))("abc")
```

And it seems to work.

Thank you for explaining this to me, as although it may still be a problem I have the necessary knowledge to work around this and avoid this undesired behaviour.

**Comment by nickbattle** [comment]
Mmm... so the create_string_equals_function lambdas would always be considered "equal", because their parameter types are the same and the body is the same, whereas the explicit string_equals_xxx functions would be different because their bodies are different. So the set of functions in should_be_true_5 has only one member, which is the first member:
```
> p card { create_string_equals_function("xyz"), create_string_equals_function("abc") }
= 1
Executed in 0.128 secs. 
```
Hmmm. OK. So perhaps my smart-arse check for function equality wasn't that smart after all. I can easily change it so that all function equality is considered false. In that case the values are all as expected.

**Comment by JaScMiller** [comment]
I can definately see the reason for function equality checking though, as the cardinality of the following set is logically 1:

```
{ create_string_equals_function("abc"), create_string_equals_function("abc") }
```

**Comment by nickbattle** [comment]
> Sorry, my reply was redundant.

Well, we got to the same result at the same time. Let's call it "independent validation" :-)

**Comment by nickbattle** [comment]
Yes, function equality is meaningful, but it is definitely complicated and I suspect it is actually not (generally) computable. I'll look into it - we need to understand the true limitations of the runtime, and perhaps we can change the interpreter or (at least) add something to the LRM.

**Comment by tomooda** [comment]
My understanding is that the equality of functions is in general not computable. But I think we can improve your "practical" definition of function equality by  having the lambda's toString output the lambda expression along with binding (referred variables and their values). At least, I believe it can handle this example.

**Comment by nickbattle** [comment]
Rather than just say that all function equality is false, it might be better to extend the equality definition to include the free variables that are attached - those would be different in the example here, being the arguments passed to the lambda. I'd just have to check the scope of the free variables that are collected. I seem to remember that (for efficiency) the runtime includes all free variables available at the function's definition, rather than working out what it might need. Comparing many values would make function equality testing more expensive, but perhaps it's rare enough that we don't mind. Alternatively, we can find the actual free variable list for the function when it is defined, but that would slow it down all the time :)

**Comment by tomooda** [comment]
Nick, if we have all function equality be false, it would make `f = f` false, which is apparently against reflexivity of equality.

**Comment by nickbattle** [comment]
> Nick, if we have all function equality be false, it would make `f = f` false, which is apparently against reflexivity of equality.

VERY good point!

**Comment by nickbattle** [comment]
@tomooda Do you know what VDMTools does here?

**Comment by tomooda** [comment]
I got an interesting result in VDMTools.
```
vdm> print card {create_string_equals_function("abc"), create_string_equals_function("xyz")}
2
vdm> print card {create_string_equals_function("abc"), create_string_equals_function("abc")}
1
vdm> 
```
I'll ask Dr. K how the functions are compared.

**Comment by JaScMiller** [comment]
@tomooda This result looks what I would expect in this case

**Comment by tomooda** [comment]
I asked Dr.K with a simplified example
```
functions
    hof : nat -> (nat -> nat)
    hof(x) == lambda y:nat & x + y;
```

Hey says VDMTool evaluates `hof(1)` to the following internal value of the function.
```
mk_SEM`CompExplFN(
    [ mk_SEM`ExplFN(
         mk_AS`TotalFnType( --- type
            [ mk_AS`NumericType( <NAT>, 167772198 ) ]
            mk_AS`AllType( -1 ),
            -1 ),
         [ [ [ mk_STKM`PatternName( --- parameters
                mk_AS`Name( [ "y" ], 167772196 ),
                mk_AS`NumericType( <NAT>, 167772198 ) ]
         1, --- Program ID
         mk_SEM`BlkEnv( --- Environment
            { mk_AS`Name( [ "x" ], 167772200 ) |->
                mk_SEM`ValTp(
                   mk_SEM`NUM( 1 ),
                   nil ) }
            <READ_ONLY> ),
         { |-> }, --- type variable information
         nil, --- function name (nil because it is a lambda expression)
         mk_AS`Name( [ "A" ], 167772161 ), --- Module Name.
         false,  --- implicit flag
         nil, --- object ref(PP only)
         <PRIVATE_AS> ), --- Access (PP only)
    nil )
```
The equality compares all this information except for the context information.
(I don't know what he means by the context information. I'm asking him about it.)
The `x+y` part is gone. I guess it's stored somewhere pointed by the program ID. I'm confirming it to Dr. K.
The following part is the environment information, the binding from the pattern matching held by the closure.
```
         mk_SEM`BlkEnv(
            { mk_AS`Name( [ "x" ], 167772200 ) |->
                mk_SEM`ValTp(
                   mk_SEM`NUM( 1 ),
                   nil ) }
            <READ_ONLY> ),
```

hof(2)'s environment information would be as the following.
```
         mk_SEM`BlkEnv(
            { mk_AS`Name( [ "x" ], 167772200 ) |->
                mk_SEM`ValTp(
                   mk_SEM`NUM( 2 ),
                   nil ) }
            <READ_ONLY> ),
```
so hof(1) is not equal to hof(2).
I guess comparing function's AST by `==` (not by `equals()`) AND binding information by `equals()` would reproduce the function's equality in VDMTools?

**Comment by tomooda** [comment]
I also tried the following spec on VDMTools.
```
functions
    hof1 : nat -> (nat -> nat)
    hof1(x) == lambda y:nat & x + y;
    hof2 : nat -> (nat -> nat)
    hof2(x) == lambda y:nat & x + y;
```
The VDMTools' interpreter says `hof1(1)` is not equal to `hof2(1)`.

**Comment by tomooda** [comment]
> The equality compares all this information except for the context information.
> (I don't know what he means by the context information. I'm asking him about it.)

The context information is the reference to source code and AST such as `167772200` in `mk_AS`Name( [ "x" ], 167772200 )`.
It makes sense that VDMTools ignore those things.

> The x+y part is gone. I guess it's stored somewhere pointed by the program ID. I'm confirming it to Dr. K.

This was correct. Dr. K says a body of a function or an operation are translated to internal execution code and are referenced by the program ID.

> I guess comparing function's AST by == (not by equals()) AND binding information by equals() would reproduce the function's equality in VDMTools?

This is wrong. We also need type information because the returned lambda could be bound to a variable with a wider type.
VDMTools also compares parameter patterns, but I'm not sure we really need it. How can we have a function value whose parameter patterns are altered? Though I'd agree it'd be more robust to compare all including parameter patterns.

**Comment by pglvdm** [comment]
Mathematically speaking function equality is not computable in general because we deal with potentially infinite domains. Thus, this issue with function equality can never be solved correctly mathematically speaking. Thus, if we will maximal be able to approximate this, but even that may be confusing to users...

**Comment by tomooda** [comment]
I agree that we can't make a perfect implementation of mathematically correct function equality.
To minimize the user (specifier)'s confusion, I'd expect the following two properties.
* valid equality: equality must be reflexive, symmetric and transitive.
* no type-2 error: mathematically inequal functions must be judged inequal while some mathematically equal functions might be judged inequal.

The issue found by Jamie belongs to type-2 error. Two different looking functions were judged as equal.
The issue in https://github.com/overturetool/overture/issues/739#issuecomment-695141487 belongs to type-1 error. It's not mathematically correct, but not a big surprise in my opinion.
The equality implemented in VDMTools looks to have type-1 errors, but I don't think it will make type-2 error.
If we want to avoid type-2 errors, Overture's function equality would need to compare the lambda's types (including polymorphic type variables and instantiation's type arguments), parameters, body expressions, and environment (bindings of free variables). The strictness of comparing lambda's body expressions is still open to discussion.
Body expresssion equality could be Java's `==` comparision or `equals()` comparison between AST nodes.

**Comment by nickbattle** [comment]
Thanks, Tomo, for investigating what VDMTools does. I agree with your ideal case of type 1 and 2 errors (false positives, and false negatives). Peter is also right that we can only ever reach an approximation here. And we should probably make it clear in the LRM what the runtime is capable of(?).

I think the best thing I can do is tighten the Overture/VDMJ checks to include the free variables (which should catch Jamie's error) and I'll also check what happens with polymorphic cases (I suspect these are evaluated-out before the function value is created - i.e. you can't create a polymorphic lambda, only a type-defined lambda via a polymorphic function, that was first instantiated).

What do people think about the idea of a warning (maybe behind `-strict`) when function values are compared?

**Comment by JaScMiller** [comment]
> 
> 
> What do people think about the idea of a warning (maybe behind `-strict`) when function values are compared?

As just a user/modeller and not someone working with overture/vdm behind under the hood, function equality was not something I ever thought of until this thread (as you can see my original report was just me being confused as to why my functions were behaving inconsistently)

However when you guys pointed out the reason (again, thank you so much this thread has been so helpful), all the strange behaviour I had been experiencing over a couple of days that I just couldn't see a pattern to suddenly made sense (functions in sets, lambdas violating measures). For this reason a warning from the outset would have probably have helped me see this a lot sooner and I would think that it's a very good idea.

**Comment by tomooda** [comment]
I agree that we need more explanation in the LRM. We can work on LRM (probably a new issue in the document repository) after we find an affordable/effective implementation in VDMJ/Overture.
I also agree that warning on function comparison (including set type of any type that involves function type in equality) is a good idea. I believe it's worth notifying.

**Comment by nickbattle** [comment]
> The VDMTools' interpreter says `hof1(1)` is not equal to `hof2(1)`.

With some simple free variable checks added, VDMJ says that hof1(1) = hof2(1), and hof1 = hof2. But there is something strange going on with polymorphic examples, like this:
```
	plus: nat -> (nat -> set of nat)
	plus(n) ==
		lambda a:nat & {a, n};

	poly[@T]: @T -> (@T -> set of @T)
	poly(n) ==
		lambda a:@T & {a, n};

	test: () -> bool
	test() ==
		let f1 = plus(1), f2 = poly[nat](1) in
			f1 = f2;
```
This is saying f1 <> f2 because the free variables for the polymorphic case includes a parameter for T (even though the function has been instantiated) and there's also something strange going on with "visible" functions being included (or not) in the free variable list - because the instantiation is in a "local" sub-context rather than the top level, like plus. So there may be bugs here that we've not encountered before. Still investigating...

**Comment by nickbattle** [comment]
OK, I think I've fixed this in VDMJ - and Overture is almost identical at this level. The details don't really matter, but I've changed which FunctionValues have free variables (most of them had, which is not necessary) and where/when free variables are imported into the runtime context as functions are executed. The comparison of functions now includes free variables (if any) but *excludes* any @T parameters (which aren't really there in a sense).

I'll do some more testing, then shift the changes over to Overture.

**Comment by nickbattle** [comment]
I've also added warnings for "=" and set enums and comprehensions. So Jamie's test spec gives:
```
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 7:51
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 7:70
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 8:51
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 8:70
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 11:51
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 11:89
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 12:51
Warning 5037: Function equality cannot be reliably computed in 'testing' (test.vdm) at line 12:89
```
That's on the lines that define the "should_be_..." constants, where the function values are added to sets. Any "=" that could be a function gives a warning; set enums with one function member *don't* but otherwise do; set comprehensions that have elements that could be functions have the warning.

Anywhere else the warning should appear?

Should this be `-strict` only?

**Comment by nickbattle** [comment]
Just pushed the basic fix to ncb/development, without the warnings.

Happy to add the warnings later, if people prefer them. And only under `-strict` or always?

**Comment by JaScMiller** [comment]
My personal opinion for what it's worth is that it should always warn

**Comment by nickbattle** [comment]
I agree Jamie. And since none of the test suite provoke the warning, it's not causing us much grief to add warnings always. I'll push the fix.

**Comment by nickbattle** [comment]
Fix now available in ncb/development.
